### ISSUE TITLE
LRIS crash due to `sig_thresh` parameter

### ISSUE THREAD

**Issue by jtmyles** [pypeit/PypeIt#1013]
I can use the `run_pypeit` command to completion when no detection threshold is set in the `.pypeit` file used, but when I set it with the following three lines:

```
[reduce]
 [[findobj]]
  sig_thresh = 3.
```

I get an error (>~20 minutes in) shown below. The full output from the `run_pypeit` command is in this gist: https://gist.github.com/jtmyles/9c3ffc937b1f2e50141f98a11803e370

Two diagnostics I will attempt are: 
- view the slit in question with `pypeit_show_2dspec`
- check all slits with `pypeit_chk_edges`

Error:
```
[WARNING] :: ERROR: Bspline sky subtraction failed after 4 iterations of bkpt spacing
[WARNING] ::        Moving on......
[INFO]    :: --------------------------REDUCING: Iteration #  2 of  4---------------------------------------------------
[WARNING] :: Object profile is zero everywhere. This aperture is junk.
Traceback (most recent call last):
  File "/home/jmyles/anaconda3/envs/pypeit/bin/run_pypeit", line 17, in <module>
    rtval = run_pypeit.main(args)
  File "/home/jmyles/anaconda3/envs/pypeit/lib/python3.7/site-packages/pypeit/scripts/run_pypeit.py", line 96, in main
    pypeIt.reduce_all()
  File "/home/jmyles/anaconda3/envs/pypeit/lib/python3.7/site-packages/pypeit/pypeit.py", line 366, in reduce_all
    std_outfile=std_outfile)
  File "/home/jmyles/anaconda3/envs/pypeit/lib/python3.7/site-packages/pypeit/pypeit.py", line 490, in reduce_exposure
    = self.reduce_one(frames, self.det, bg_frames, std_outfile=std_outfile)
  File "/home/jmyles/anaconda3/envs/pypeit/lib/python3.7/site-packages/pypeit/pypeit.py", line 659, in reduce_one
    obstime=self.obstime)
  File "/home/jmyles/anaconda3/envs/pypeit/lib/python3.7/site-packages/pypeit/reduce.py", line 387, in run
    = self.extract(self.global_sky, self.sobjs_obj)
  File "/home/jmyles/anaconda3/envs/pypeit/lib/python3.7/site-packages/pypeit/reduce.py", line 287, in extract
    show=self.reduce_show)
  File "/home/jmyles/anaconda3/envs/pypeit/lib/python3.7/site-packages/pypeit/reduce.py", line 980, in local_skysub_extract
    use_2dmodel_mask=self.par['reduce']['extraction']['use_2dmodel_mask'])
  File "/home/jmyles/anaconda3/envs/pypeit/lib/python3.7/site-packages/pypeit/core/skysub.py", line 739, in local_skysub_extract
    if sobjs[iobj].OPT_MASK.any():
AttributeError: 'NoneType' object has no attribute 'any'
```

**Comment by profxj** [comment]
I believe this was fixed.  But reopen if not
