### ISSUE TITLE
issue with requirement check using pytest==6.1.1

### ISSUE THREAD

**Issue by csnap001** [pypeit/PypeIt#1074]
When trying to use pypeit with the latest version of pytest the following issue happens:`Traceback (most recent call last):
  File "/Users/chrismac/opt/anaconda3/bin/pypeit_show_2dspec", line 4, in <module>
    __import__('pkg_resources').run_script('pypeit==1.1.1', 'pypeit_show_2dspec')
  File "/Users/chrismac/opt/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 650, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/chrismac/opt/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1446, in run_script
    exec(code, namespace, namespace)
  File "/Users/chrismac/opt/anaconda3/lib/python3.7/site-packages/pypeit-1.1.1-py3.7-macosx-10.9-x86_64.egg/EGG-INFO/scripts/pypeit_show_2dspec", line 11, in <module>
    import pypeit.scripts.show_2dspec as show_2dspec
  File "/Users/chrismac/opt/anaconda3/lib/python3.7/site-packages/pypeit-1.1.1-py3.7-macosx-10.9-x86_64.egg/pypeit/__init__.py", line 33, in <module>
    from pypeit import check_requirements  # THIS IMPORT DOES THE CHECKING.  KEEP IT
  File "/Users/chrismac/opt/anaconda3/lib/python3.7/site-packages/pypeit-1.1.1-py3.7-macosx-10.9-x86_64.egg/pypeit/check_requirements.py", line 19, in <module>
    + 'Please update to version >= {0}'.format(version))
ImportError: Your version of pytest is incompatible with PypeIt.  Please update to version >= 3.0.7`

This may just be an issue with installing pytest into a conda environment using pip. I forced the code to print the versions that are loaded in the check_requirements.py code and pytest was listed as 0.0.0. When I downgraded to pytest 6.0.0 using pip install pytest==6.0.0 everything worked as expected. 
Just thought I'd mention this as a warning and solution to this strange problem. likely the metadata for pytest wasn't loaded properly during an install

**Comment by profxj** [comment]
It is unclear what version of PypeIt you are running.

**Comment by csnap001** [comment]
My apologies, pypeit==1.1.1

**Comment by profxj** [comment]
Please try the current version (1.2).
Thanks.
