### ISSUE TITLE
run_pypeit -c fails for NIRES

### ISSUE THREAD

**Issue by jhennawi** [pypeit/PypeIt#1119]
There appears to be a bug in run_pypeit for the -c option.  Data and pypeit file are at this link. 

https://www.dropbox.com/sh/g6f0ou5in5pywoj/AAC-XKVLowJlsxJhkRF5jDKja?dl=0

This pypeit file runs just fine if I don't set the -c option. Traceback is below: 

Traceback (most recent call last):
  File "/Users/joe/opt/anaconda3/bin//run_pypeit", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/Users/joe/python/PypeIt/bin/run_pypeit", line 16, in <module>
    sys.exit(run_pypeit.main(run_pypeit.parse_args()))
  File "/Users/joe/python/PypeIt/pypeit/scripts/run_pypeit.py", line 114, in main
    pypeIt.calib_all()
  File "/Users/joe/python/PypeIt/pypeit/pypeit.py", line 278, in calib_all
    self.caliBrate.set_config(grp_frames[0], self.det, self.par['calibrations'])
  File "/Users/joe/python/PypeIt/pypeit/calibrations.py", line 213, in set_config
    self.calib_ID = int(self.fitstbl['calib'][frame])
ValueError: invalid literal for int() with base 10: 'all'

**Comment by profxj** [comment]
you should first add a test to either the unit tests or the Dev suite.

**Comment by jhennawi** [comment]
I think it makes more sense for the individual that fixes this issue to add this test to their PR.
