### ISSUE TITLE
Error running `run_pypeit` or `pypeit_setup`: bad pytest version

### ISSUE THREAD

**Issue by danmoser** [pypeit/PypeIt#1127]
When running `run_pypeit -h`, I get the following warning. However my pytest version matches the requirement.

```
Traceback (most recent call last):
  File "/Users/dfaes/anaconda3/envs/my37env/bin/run_pypeit", line 12, in <module>
    from pypeit.scripts import run_pypeit
  File "/Users/dfaes/anaconda3/envs/my37env/lib/python3.7/site-packages/pypeit/__init__.py", line 33, in <module>
    from pypeit import check_requirements  # THIS IMPORT DOES THE CHECKING.  KEEP IT
  File "/Users/dfaes/anaconda3/envs/my37env/lib/python3.7/site-packages/pypeit/check_requirements.py", line 19, in <module>
    + 'Please update to version >= {0}'.format(version))
ImportError: Your version of pytest is incompatible with PypeIt.  Please update to version >= 6.0.0
```

My Python3.7 conda environment:

```
# Name                    Version                   Build  Channel
appnope                   0.1.2           py37hecd8cb5_1001  
astropy                   4.2              py37h9ed2024_0  
attrs                     20.3.0             pyhd3eb1b0_0  
backcall                  0.2.0                      py_0  
blas                      1.0                         mkl  
brotlipy                  0.7.0           py37h9ed2024_1003  
ca-certificates           2020.12.8            hecd8cb5_0  
certifi                   2020.12.5        py37hecd8cb5_0  
cffi                      1.14.4           py37h2125817_0  
chardet                   4.0.0           py37hecd8cb5_1003  
configobj                 5.0.6                    py37_1  
cryptography              3.3.1            py37hbcfaee0_0  
cycler                    0.10.0                   py37_0  
decorator                 4.4.2                      py_0  
extension-helpers         0.1                      pypi_0    pypi
freetype                  2.10.4               ha233b18_0  
ginga                     3.1.0                    py37_0    http://ssb.stsci.edu/astroconda
idna                      2.10                       py_0  
importlib-metadata        2.0.0                      py_1  
importlib_metadata        2.0.0                         1  
iniconfig                 1.1.1                      py_0  
intel-openmp              2019.4                      233  
ipython                   7.19.0           py37h01d92e1_0  
ipython_genutils          0.2.0              pyhd3eb1b0_1  
jedi                      0.18.0           py37hecd8cb5_0  
joblib                    1.0.0              pyhd3eb1b0_0  
jpeg                      9b                   he5867d9_2  
kiwisolver                1.3.0            py37h23ab428_0  
lcms2                     2.11                 h92f6f08_0  
libcxx                    10.0.0                        1  
libedit                   3.1.20191231         h1de35cc_1  
libffi                    3.3                  hb1e8313_2  
libgfortran               3.0.1                h93005f0_2  
libllvm10                 10.0.1               h76017ad_5  
libpng                    1.6.37               ha441bb4_0  
libtiff                   4.1.0                hcb84e12_1  
linetools                 0.3.dev2231              pypi_0    pypi
llvm-openmp               10.0.0               h28b9765_0  
llvmlite                  0.34.0           py37h739e7dc_4  
lz4-c                     1.9.2                h79c402e_3  
matplotlib                3.3.2                hecd8cb5_0  
matplotlib-base           3.3.2            py37h181983e_0  
mkl                       2019.4                      233  
mkl-service               2.3.0            py37h9ed2024_0  
mkl_fft                   1.2.0            py37hc64f4ea_0  
mkl_random                1.1.1            py37h959d312_0  
more-itertools            8.6.0              pyhd3eb1b0_0  
ncurses                   6.2                  h0a44026_1  
numba                     0.51.2           py37h959d312_1  
numpy                     1.19.2           py37h456fd55_0  
numpy-base                1.19.2           py37hcfb5961_0  
olefile                   0.46                     py37_0  
openssl                   1.1.1i               h9ed2024_0  
packaging                 20.8               pyhd3eb1b0_0  
parso                     0.7.0                      py_0  
pexpect                   4.8.0              pyhd3eb1b0_3  
pickleshare               0.7.5           pyhd3eb1b0_1003  
pillow                    8.1.0            py37h5270095_0  
pip                       20.3.3           py37hecd8cb5_0  
pluggy                    0.13.1                   py37_0  
prompt-toolkit            3.0.8                      py_0  
ptyprocess                0.7.0              pyhd3eb1b0_2  
py                        1.10.0             pyhd3eb1b0_0  
pycparser                 2.20                       py_2  
pyerfa                    1.7.1.1          py37h9ed2024_1  
pygments                  2.7.4              pyhd3eb1b0_0  
pyopenssl                 20.0.1             pyhd3eb1b0_1  
pyparsing                 2.4.7                      py_0  
pypeit                    1.3.0                    pypi_0    pypi
pyside2                   5.15.2                   pypi_0    pypi
pysocks                   1.7.1            py37hecd8cb5_0  
pytest                    6.2.1            py37hecd8cb5_0  
python                    3.7.9                h26836e1_0  
python-dateutil           2.8.1                      py_0  
pyyaml                    5.3.1            py37haf1e3a3_1  
qtpy                      1.9.0                      py_0  
readline                  8.0                  h1de35cc_0  
requests                  2.25.1             pyhd3eb1b0_0  
scikit-learn              0.23.2           py37h959d312_0  
scipy                     1.5.2            py37h912ce22_0  
setuptools                51.1.2           py37hecd8cb5_4  
shiboken2                 5.15.2                   pypi_0    pypi
six                       1.15.0           py37hecd8cb5_0  
sqlite                    3.33.0               hffcf06c_0  
threadpoolctl             2.1.0              pyh5ca1d4c_0  
tk                        8.6.10               hb0a8c7a_0  
toml                      0.10.1                     py_0  
tornado                   6.1              py37h9ed2024_0  
traitlets                 5.0.5                      py_0  
urllib3                   1.26.2             pyhd3eb1b0_0  
wcwidth                   0.2.5                      py_0  
wheel                     0.36.2             pyhd3eb1b0_0  
xz                        5.2.5                h1de35cc_0  
yaml                      0.2.5                haf1e3a3_0  
zipp                      3.4.0              pyhd3eb1b0_0  
zlib                      1.2.11               h1de35cc_3  
zstd                      1.4.5                h41d2c2f_0  
```

**Comment by profxj** [comment]
I believe this issue has gone away.
