### ISSUE TITLE
Break in 1d coadding

### ISSUE THREAD

**Issue by csnap001** [pypeit/PypeIt#1163]
This is a minor issue and doesn't occur regularly, but thought I would bring it up so that the issue is on your radar.
When doing 1d coadding and a spectrum in LRISb I got the following traceback

    Traceback (most recent call last):
      File "/Users/chrismac/opt/anaconda3/bin/pypeit_coadd_1dspec", line 11, in <module>
        sys.exit(entry_point())
      File "/Users/chrismac/opt/anaconda3/lib/python3.8/site-packages/pypeit/scripts/coadd_1dspec.py", line 248, in entry_point
        main(parse_args())
      File "/Users/chrismac/opt/anaconda3/lib/python3.8/site-packages/pypeit/scripts/coadd_1dspec.py", line 241, in main
        coAdd1d.run()
      File "/Users/chrismac/opt/anaconda3/lib/python3.8/site-packages/pypeit/coadd1d.py", line 181, in run
        self.wave_coadd, self.flux_coadd, self.ivar_coadd, self.mask_coadd = self.coadd()
      File "/Users/chrismac/opt/anaconda3/lib/python3.8/site-packages/pypeit/coadd1d.py", line 284, in coadd
        return coadd.multi_combspec(
      File "/Users/chrismac/opt/anaconda3/lib/python3.8/site-packages/pypeit/core/coadd.py", line 2340, in multi_combspec
        wave_stack, flux_stack, ivar_stack, mask_stack = combspec(
      File "/Users/chrismac/opt/anaconda3/lib/python3.8/site-packages/pypeit/core/coadd.py", line 2208, in combspec
        fluxes_scale, ivars_scale, scales, scale_method_used = scale_spec_stack(
      File "/Users/chrismac/opt/anaconda3/lib/python3.8/site-packages/pypeit/core/coadd.py", line 2086, in scale_spec_stack
        fluxes_scale[:, iexp], ivars_scale[:, iexp], scales[:, iexp], scale_method_iexp = scale_spec(
      File "/Users/chrismac/opt/anaconda3/lib/python3.8/site-packages/pypeit/core/coadd.py", line 1251, in scale_spec
        flux_ref_int, ivar_ref_int, mask_ref_int = interp_spec(wave, wave_ref, flux_ref, ivar_ref, mask_ref)
      File "/Users/chrismac/opt/anaconda3/lib/python3.8/site-packages/pypeit/core/coadd.py", line 656, in interp_spec
        fluxes_inter, ivars_inter, masks_inter = interp_oned(wave_new, waves, fluxes, ivars, masks)
      File "/Users/chrismac/opt/anaconda3/lib/python3.8/site-packages/pypeit/core/coadd.py", line 621, in interp_oned
        flux_new = scipy.interpolate.interp1d(wave_old[wave_mask], flux_old[wave_mask], kind='cubic',
      File "/Users/chrismac/opt/anaconda3/lib/python3.8/site-packages/scipy/interpolate/interpolate.py", line 458, in __init__
        self._y = self._reshape_yi(self.y)
      File "/Users/chrismac/opt/anaconda3/lib/python3.8/site-packages/scipy/interpolate/polyint.py", line 106, in _reshape_yi
        return yi.reshape((yi.shape[0], -1))
    ValueError: cannot reshape array of size 0 into shape (0,newaxis)

From what I can tell, after a little bit of debugging, this is caused by nan values in the flux_stack array in coadd.py around line 797. I made the following edits to alleviate this issue, but it causes some strange behavior at the location of the nan values:

     795  ivar_stack[np.isnan(ivar_stack)] = 0.001
     796  flux_stack[np.isnan(flux_stack)] = 0.001
     797  sn_val = flux_stack*np.sqrt(ivar_stack)
     798  sn_val[np.isnan(sn_val)] = 0.001

The problem values were outside of the wavelength range I was concerned with, so I accepted it and moved on. However, there may be some benefit in the future for dealing with nan values more neatly in the calculations here.

**Comment by jhennawi** [comment]
Thanks for digging in @csnap001. Would it be possible to make the spec1d files that reproduce this bug available in the PypeIt users Slack?

**Comment by csnap001** [comment]
Sure, is there a preferred channel?

**Comment by jhennawi** [comment]
#coadd1d Thanks!

**Comment by jhennawi** [comment]
@csnap001 can I close this issue. The problem was I think with your sensitivity function and not this code.

**Comment by csnap001** [comment]
Closing now.
