### ISSUE TITLE
Adding Gemini GNIRS 111 l/mm grating

### ISSUE THREAD

**Issue by lukasfurtak** [pypeit/PypeIt#1309]
Hi,

I am currently trying to reduce some Gemini GNIRS data and from running `run_pypeit` I get the feedback

```
[INFO]    :: util.py 509 parse_pypeit_file() - Loading the reduction file
[INFO]    :: util.py 535 parse_pypeit_file() - Found 96 raw data frames
[INFO]    :: util.py 557 parse_pypeit_file() - Input file loaded successfully
[INFO]    :: pypeit.py 101 __init__() - Loaded spectrograph gemini_gnirs
[INFO]    :: pypeit.py 117 __init__() - Setting configuration-specific parameters using N20211026S0189.fits

[ERROR]   :: gemini_gnirs.py 207 config_specific_par() - Unrecognized GNIRS dispname
Traceback (most recent call last):
  File "/opt/miniconda3/envs/spectroscopy/bin/run_pypeit", line 11, in <module>
    sys.exit(RunPypeIt.entry_point())
  File "/opt/miniconda3/envs/spectroscopy/lib/python3.9/site-packages/pypeit/scripts/scriptbase.py", line 110, in entry_point
    cls.main(cls.parse_args())
  File "/opt/miniconda3/envs/spectroscopy/lib/python3.9/site-packages/pypeit/scripts/run_pypeit.py", line 124, in main
    pypeIt = pypeit.PypeIt(args.pypeit_file, verbosity=args.verbosity,
  File "/opt/miniconda3/envs/spectroscopy/lib/python3.9/site-packages/pypeit/pypeit.py", line 119, in __init__
    spectrograph_cfg_lines = self.spectrograph.config_specific_par(config_specific_file).to_config()
  File "/opt/miniconda3/envs/spectroscopy/lib/python3.9/site-packages/pypeit/spectrographs/gemini_gnirs.py", line 207, in config_specific_par
    msgs.error('Unrecognized GNIRS dispname')
  File "/opt/miniconda3/envs/spectroscopy/lib/python3.9/site-packages/pypeit/pypmsgs.py", line 184, in error
    raise PypeItError(msg)
pypeit.pypmsgs.PypeItError: Unrecognized GNIRS dispname
```

Our observations were taken with the 111 l/mm grating, i.e. the `dispname` for these is: 111/mmSB_G5534

As I understand it from looking at the source code for GNIRS, this is because PypeIt only supports the 32 l/mm and 10 l/mm gratings of GNIRS so far. Would it therefore be possible to add the 111 l/mm one?

Also, since this is a fairly commonly used configuration of GNIRS, I would be happy to add it myself to PypeIt or contribute to it if I can and if there is noone already working on it.

**Comment by profxj** [comment]
That would great.  Please join the Users Slack for additional 
guidance. Thx!

**Comment by kbwestfall** [comment]
Any progress to report here?
