### ISSUE TITLE
Trouble with run_pypeit

### ISSUE THREAD

**Issue by Junjie-Jin** [pypeit/PypeIt#1373]
Hi,

When running the "run_pypeit shane_kast_blue_A.pypeit -o" in "Step by Step Example",  I got the following error:

```
Traceback (most recent call last):
  File "/opt/anaconda3/envs/pypeit/bin/run_pypeit", line 8, in <module>
    sys.exit(RunPypeIt.entry_point())
  File "/opt/anaconda3/envs/pypeit/lib/python3.9/site-packages/pypeit/scripts/scriptbase.py", line 110, in entry_point
    cls.main(cls.parse_args())
  File "/opt/anaconda3/envs/pypeit/lib/python3.9/site-packages/pypeit/scripts/run_pypeit.py", line 142, in main
    pypeIt.reduce_all()
  File "/opt/anaconda3/envs/pypeit/lib/python3.9/site-packages/pypeit/pypeit.py", line 388, in reduce_all
    std_spec2d, std_sobjs = self.reduce_exposure(frames, bg_frames=bg_frames)
  File "/opt/anaconda3/envs/pypeit/lib/python3.9/site-packages/pypeit/pypeit.py", line 597, in reduce_exposure
    = self.extract_one(frames, self.det, sciImg_list[i], objFind_list[i],
  File "/opt/anaconda3/envs/pypeit/lib/python3.9/site-packages/pypeit/pypeit.py", line 885, in extract_one
    tilts = self.redux.run_extraction(final_global_sky, sobjs_obj, ra=self.fitstbl["ra"][frames[0]],
  File "/opt/anaconda3/envs/pypeit/lib/python3.9/site-packages/pypeit/extraction.py", line 381, in run_extraction
    self.refframe_correct(ra, dec, obstime, sobjs=self.sobjs)
  File "/opt/anaconda3/envs/pypeit/lib/python3.9/site-packages/pypeit/extraction.py", line 515, in refframe_correct
    vel, vel_corr = wave.geomotion_correct(radec, obstime,
  File "/opt/anaconda3/envs/pypeit/lib/python3.9/site-packages/pypeit/core/wave.py", line 58, in geomotion_correct
    vel = geomotion_calculate(radec, time, longitude, latitude, elevation, refframe)
  File "/opt/anaconda3/envs/pypeit/lib/python3.9/site-packages/pypeit/core/wave.py", line 28, in geomotion_calculate
    return geomotion_velocity(obstime, radec, frame=refframe)
  File "/opt/anaconda3/envs/pypeit/lib/python3.9/site-packages/pypeit/core/wave.py", line 93, in geomotion_velocity
    op, ov = time.location.get_gcrs_posvel(time)
  File "/opt/anaconda3/envs/pypeit/lib/python3.9/site-packages/astropy/coordinates/earth.py", line 735, in get_gcrs_posvel
    cirs_to_itrs_mat(obstime),
  File "/opt/anaconda3/envs/pypeit/lib/python3.9/site-packages/astropy/coordinates/builtin_frames/intermediate_rotation_transforms.py", line 52, in cirs_to_itrs_mat
    xp, yp = get_polar_motion(time)
  File "/opt/anaconda3/envs/pypeit/lib/python3.9/site-packages/astropy/coordinates/builtin_frames/utils.py", line 47, in get_polar_motion
    iers_table = iers.earth_orientation_table.get()
  File "/opt/anaconda3/envs/pypeit/lib/python3.9/site-packages/astropy/utils/state.py", line 40, in get
    return cls.validate(cls._value)
  File "/opt/anaconda3/envs/pypeit/lib/python3.9/site-packages/astropy/utils/iers/iers.py", line 862, in validate
    value = IERS_Auto.open()
  File "/opt/anaconda3/envs/pypeit/lib/python3.9/site-packages/astropy/utils/iers/iers.py", line 694, in open
    cls.iers_table = cls.read(file=filename)
  File "/opt/anaconda3/envs/pypeit/lib/python3.9/site-packages/astropy/utils/iers/iers.py", line 547, in read
    iers_a = super().read(file, format='cds', readme=readme)
  File "/opt/anaconda3/envs/pypeit/lib/python3.9/site-packages/astropy/table/connect.py", line 62, in __call__
    out = self.registry.read(cls, *args, **kwargs)
  File "/opt/anaconda3/envs/pypeit/lib/python3.9/site-packages/astropy/io/registry/core.py", line 199, in read
    data = reader(*args, **kwargs)
  File "/opt/anaconda3/envs/pypeit/lib/python3.9/site-packages/astropy/io/ascii/connect.py", line 18, in io_read
    return read(filename, **kwargs)
  File "/opt/anaconda3/envs/pypeit/lib/python3.9/site-packages/astropy/io/ascii/ui.py", line 376, in read
    dat = reader.read(table)
  File "/opt/anaconda3/envs/pypeit/lib/python3.9/site-packages/astropy/io/ascii/cds.py", line 343, in read
    return super().read(table)
  File "/opt/anaconda3/envs/pypeit/lib/python3.9/site-packages/astropy/io/ascii/core.py", line 1381, in read
    table = self.outputter(self.header.cols, self.meta)
  File "/opt/anaconda3/envs/pypeit/lib/python3.9/site-packages/astropy/io/ascii/core.py", line 1117, in __call__
    self._convert_vals(cols)
  File "/opt/anaconda3/envs/pypeit/lib/python3.9/site-packages/astropy/io/ascii/core.py", line 1060, in _convert_vals
    raise ValueError(f'Column {col.name} failed to convert: {last_err}')
ValueError: Column year failed to convert: invalid literal for int() with base 10: '<!'
```

I wonder if it is a bug in integer conversion?

I have installed the Pypelt via conda.

**Comment by profxj** [comment]
@Junjie-Jin -- join the PypeIt Slack and seek help there.
  This test is being run all the time successfully, i.e. it must be
  peculiar to your machine.
