### ISSUE TITLE
Ginga not functional

### ISSUE THREAD

**Issue by csnap001** [pypeit/PypeIt#1457]
I'm running on MacOS Monterey(v12.4). I've updated to pypeit 1.10.0 and now ginga is not functional. Here is the traceback:
  File "/Users/chrismac/opt/anaconda3/bin/ginga", line 8, in <module>
    sys.exit(_main())
  File "/Users/chrismac/opt/anaconda3/lib/python3.9/site-packages/ginga/rv/main.py", line 753, in _main
    reference_viewer(sys.argv)
  File "/Users/chrismac/opt/anaconda3/lib/python3.9/site-packages/ginga/rv/main.py", line 748, in reference_viewer
    viewer.main(options, args)
  File "/Users/chrismac/opt/anaconda3/lib/python3.9/site-packages/ginga/rv/main.py", line 378, in main
    from ginga.rv.Control import GingaShell, GuiLogHandler
  File "/Users/chrismac/opt/anaconda3/lib/python3.9/site-packages/ginga/rv/Control.py", line 28, in <module>
    from ginga.util import catalog, iohelper, loader, toolbox
  File "/Users/chrismac/opt/anaconda3/lib/python3.9/site-packages/ginga/util/toolbox.py", line 14, in <module>
    from astropy.utils.data import _find_pkg_data_path
ImportError: cannot import name '_find_pkg_data_path' from 'astropy.utils.data' (/Users/chrismac/opt/anaconda3/lib/python3.9/site-packages/astropy/utils/data.py)

I attempted to comment out this import which allows for ginga to open when I run "ginga --modules=RC". However, when I then try to run pypeit_show_2dspec I get the following traceback:

Traceback (most recent call last):
  File "/Users/chrismac/opt/anaconda3/bin/pypeit_show_2dspec", line 8, in <module>
    sys.exit(Show2DSpec.entry_point())
  File "/Users/chrismac/opt/anaconda3/lib/python3.9/site-packages/pypeit/scripts/scriptbase.py", line 110, in entry_point
    cls.main(cls.parse_args())
  File "/Users/chrismac/opt/anaconda3/lib/python3.9/site-packages/pypeit/scripts/show_2dspec.py", line 126, in main
    spec2DObj = spec2dobj.Spec2DObj.from_file(args.file, detname, chk_version=False)
  File "/Users/chrismac/opt/anaconda3/lib/python3.9/site-packages/pypeit/spec2dobj.py", line 129, in from_file
    slf = super().from_hdu(hdul, hdu_prefix=f'{detname}-', chk_version=chk_version)
  File "/Users/chrismac/opt/anaconda3/lib/python3.9/site-packages/pypeit/datamodel.py", line 1394, in from_hdu
    = cls._parse(hdu, ext=ext, ext_pseudo=ext_pseudo, 
  File "/Users/chrismac/opt/anaconda3/lib/python3.9/site-packages/pypeit/datamodel.py", line 1007, in _parse
    data, dvpassed, dtpassed, _ = t._parse(_hdu[hduindx])
  File "/Users/chrismac/opt/anaconda3/lib/python3.9/site-packages/pypeit/datamodel.py", line 1098, in _parse
    _d = {key:val if cls.datamodel[key]['otype'] == np.ndarray or val is None else val[0] 
  File "/Users/chrismac/opt/anaconda3/lib/python3.9/site-packages/pypeit/datamodel.py", line 1098, in <dictcomp>
    _d = {key:val if cls.datamodel[key]['otype'] == np.ndarray or val is None else val[0] 
TypeError: 'int' object is not subscriptable

I'm using --det=2, but this used to be functional when I was working with v1.3.3. I checked my astropy (v4.3) and found that that function doesn't exist for the version I have which meets the requirements according to the pypeit documentation. Thoughts?

**Comment by jhennawi** [comment]
Can you indicate your ginga version number. I suspect that is the issue, i.e. this looks like a ginga issue. 

Also, note the proper way to launch ginga now from the command line is: 

ginga --modules=RC,SlitWavelength

If that is not listed in our docs please let us know and we will fix it.

**Comment by kbwestfall** [comment]
Another thing to check: This actually looks like a typical error you get when you try to read an output pypeit file that was produced with a previous version of the code.  Is the file you're trying to read also reduced by pypeit version 1.10.0?  If not, try re-reducing it.

**Comment by csnap001** [comment]
@kbwestfall this file was produced by pypeit v1.10.0. Although it overwrote a file that was previously produced with an earlier version.
@jhennawi ginga version is 3.0.1 and I did not see that command in the docs.

**Comment by csnap001** [comment]
I've now attempted using ginga --modules=RC,SlitWavelength, but I receive what looks like the same traceback:

  File "/Users/chrismac/opt/anaconda3/bin/ginga", line 8, in <module>
    sys.exit(_main())
  File "/Users/chrismac/opt/anaconda3/lib/python3.9/site-packages/ginga/rv/main.py", line 753, in _main
    reference_viewer(sys.argv)
  File "/Users/chrismac/opt/anaconda3/lib/python3.9/site-packages/ginga/rv/main.py", line 748, in reference_viewer
    viewer.main(options, args)
  File "/Users/chrismac/opt/anaconda3/lib/python3.9/site-packages/ginga/rv/main.py", line 378, in main
    from ginga.rv.Control import GingaShell, GuiLogHandler
  File "/Users/chrismac/opt/anaconda3/lib/python3.9/site-packages/ginga/rv/Control.py", line 28, in <module>
    from ginga.util import catalog, iohelper, loader, toolbox
  File "/Users/chrismac/opt/anaconda3/lib/python3.9/site-packages/ginga/util/toolbox.py", line 14, in <module>
    from astropy.utils.data import _find_pkg_data_path
ImportError: cannot import name '_find_pkg_data_path' from 'astropy.utils.data' (/Users/chrismac/opt/anaconda3/lib/python3.9/site-packages/astropy/utils/data.py)

It would seem this is a conflict with astropy, but this issue occurred when I used the latest version of astropy as well. Not sure what to make of this.

**Comment by profxj** [comment]
@csnap001 - have you posted on the Ginga GitHub?

get that sorted out and let us know if there is still an issue in PypeIt.
thx
