### ISSUE TITLE
DEIMOS slitspatnum bug

### ISSUE THREAD

**Issue by SunilSimha** [pypeit/PypeIt#1501]
Hi,

I want to reduce some DEIMOS MoS data but I'm only interested in a particular object. Therefore, I tried using the `slitspatnum` parameter as follows:
```
# Auto-generated PypeIt input file using PypeIt version: 1.11.1.dev1+g4ad54968d
# UTC 2022-11-05T21:17:26.567

# User-defined execution parameters
[rdx]
  spectrograph = keck_deimos
  slitspatnum = 6:224
  #[baseprocess]
  #    use_biasimage = False
[calibrations]
# [[slitedges]]
#   use_maskdesign = True
#   minimum_slit_length = 3.
#   minimum_slit_length_sci = None
#   minimum_slit_gap = 0.
# [[flatfield]] 
#   tweak_slits = False
[reduce]
[[slitmask]]
    #use_alignbox = True
    #assign_obj = True
    extract_missing_objs = True
  [[findobj]]
    snr_thresh = 3.
    #find_trim_edge = 6,6
  [[extraction]]
    use_2dmodel_mask = False

# Setup
setup read
Setup D:
  amp: '"SINGLE:B"'
  binning: 1,1
  decker: '2011_1'
  dispangle: 7000.04931641
  dispname: 600ZD
  filter1: GG455
setup end
```

I get the following error: 
```
Traceback (most recent call last):
  File "/home/sunil/anaconda3/bin/run_pypeit", line 33, in <module>
    sys.exit(load_entry_point('pypeit', 'console_scripts', 'run_pypeit')())
  File "/home/sunil/Python/PypeIt/pypeit/scripts/scriptbase.py", line 110, in entry_point
    cls.main(cls.parse_args())
  File "/home/sunil/Python/PypeIt/pypeit/scripts/run_pypeit.py", line 113, in main
    logname=logname, show=args.show)
  File "/home/sunil/Python/PypeIt/pypeit/pypeit.py", line 126, in __init__
    merge_with=self.pypeItFile.cfg_lines)
  File "/home/sunil/Python/PypeIt/pypeit/par/pypeitpar.py", line 4364, in from_cfg_lines
    return cls.from_dict(cfg)
  File "/home/sunil/Python/PypeIt/pypeit/par/pypeitpar.py", line 4425, in from_dict
    kwargs[pk] = ReduxPar.from_dict(cfg[pk]) if pk in k else None
  File "/home/sunil/Python/PypeIt/pypeit/par/pypeitpar.py", line 2354, in from_dict
    raise IOError("You cannot set both detnum and slitspatnum!  Causes serious SpecObjs output challenges..")
OSError: You cannot set both detnum and slitspatnum!  Causes serious SpecObjs output challenges..
```
I believe this is because PypeIt has internally set the default values for `detnum` earlier and is therefore tripping this `raise` statement.

**Comment by kbwestfall** [comment]
Closing because this should have been addressed in #1511 .
