### ISSUE TITLE
sensfunc not working when skip_optimal = True

### ISSUE THREAD

**Issue by BenjaminNavarrete** [pypeit/PypeIt#1521]
Hi! I'm using pypeit to reduce Magellan/MagE galaxy spectra. Particularly, I have followed the reduction tip and set `use_2dmodel_mask=False` in my `.pypeit` file for the reduction, because I have huge emission lines in the slits compared to faint continuum. I confirmed that this worked very well, but it needs boxcar extraction (If I include both optimal and boxcar, it does not properly extract the sky around the emission lines) so I set `skip_optimal=True`. The problem is that when I try to continue with the flux calibration, I get the following error:

`[ERROR]   :: Flux not available for OPT_COUNTS.  Try the other 
Traceback (most recent call last):
  File "/home/benjamin/anaconda3/envs/pypeit/bin/pypeit_sensfunc", line 8, in <module>
    sys.exit(SensFunc.entry_point())
  File "/home/benjamin/anaconda3/envs/pypeit/lib/python3.9/site-packages/pypeit/scripts/scriptbase.py", line 110, in entry_point
    cls.main(cls.parse_args())
  File "/home/benjamin/anaconda3/envs/pypeit/lib/python3.9/site-packages/pypeit/scripts/sensfunc.py", line 145, in main
    sensobj = sensfunc.SensFunc.get_instance(args.spec1dfile, outfile, par['sensfunc'],
  File "/home/benjamin/anaconda3/envs/pypeit/lib/python3.9/site-packages/pypeit/sensfunc.py", line 147, in get_instance
    return next(c for c in cls.__subclasses__()
  File "/home/benjamin/anaconda3/envs/pypeit/lib/python3.9/site-packages/pypeit/sensfunc.py", line 845, in __init__
    super().__init__(spec1dfile, sensfile, par=par, debug=debug)
  File "/home/benjamin/anaconda3/envs/pypeit/lib/python3.9/site-packages/pypeit/sensfunc.py", line 195, in __init__
    wave, counts, counts_ivar, counts_mask, self.meta_spec, header = sobjs_std.unpack_object(ret_flam=False)
  File "/home/benjamin/anaconda3/envs/pypeit/lib/python3.9/site-packages/pypeit/specobjs.py", line 206, in unpack_object
    msgs.error("Flux not available for {}.  Try the other ".format(flux_key))
  File "/home/benjamin/anaconda3/envs/pypeit/lib/python3.9/site-packages/pypeit/pypmsgs.py", line 185, in error
    raise PypeItError(msg)
pypeit.pypmsgs.PypeItError: Flux not available for OPT_COUNTS.  Try the other `

It says that I should try with "the other", I assume it refers to the boxcar counts. I have searched for some parameters to change or how to tell the pipeline to consider the boxcar counts instead of the non-existent optimal, but without success. If someone can guide me on how to do this, or if it cannot be done, I would really appreciate it. 

Thanks,
Benjamin

**Comment by profxj** [comment]
At present, the sensitivity function code does require an OPT extraction.
We should consider modifying that.

Until then, I suggest you extract the standard stars in a separate PypeIt file without setting `skip_optimal=True`
