### ISSUE TITLE
Issue with detect_slit_edges in trace.py

### ISSUE THREAD

**Issue by charliekilpatrick** [pypeit/PypeIt#1529]
numpy==1.24.1 no longer supports "numpy.float" leading to the following error:

```
Traceback (most recent call last):
  File "/Users/ckilpatrick/scripts/miniconda3/envs/pypeit/bin/run_pypeit", line 8, in <module>
    sys.exit(RunPypeIt.entry_point())
  File "/Users/ckilpatrick/scripts/miniconda3/envs/pypeit/lib/python3.9/site-packages/pypeit/scripts/scriptbase.py", line 110, in entry_point
    cls.main(cls.parse_args())
  File "/Users/ckilpatrick/scripts/miniconda3/envs/pypeit/lib/python3.9/site-packages/pypeit/scripts/run_pypeit.py", line 126, in main
    pypeIt.reduce_all()
  File "/Users/ckilpatrick/scripts/miniconda3/envs/pypeit/lib/python3.9/site-packages/pypeit/pypeit.py", line 410, in reduce_all
    std_spec2d, std_sobjs = self.reduce_exposure(frames, bg_frames=bg_frames)
  File "/Users/ckilpatrick/scripts/miniconda3/envs/pypeit/lib/python3.9/site-packages/pypeit/pypeit.py", line 557, in reduce_exposure
    self.caliBrate = self.calib_one(frames, self.det)
  File "/Users/ckilpatrick/scripts/miniconda3/envs/pypeit/lib/python3.9/site-packages/pypeit/pypeit.py", line 696, in calib_one
    caliBrate.run_the_steps()
  File "/Users/ckilpatrick/scripts/miniconda3/envs/pypeit/lib/python3.9/site-packages/pypeit/calibrations.py", line 834, in run_the_steps
    getattr(self, f'get_{step}')()
  File "/Users/ckilpatrick/scripts/miniconda3/envs/pypeit/lib/python3.9/site-packages/pypeit/calibrations.py", line 698, in get_slits
    self.edges = edgetrace.EdgeTraceSet(self.traceImage, self.spectrograph,
  File "/Users/ckilpatrick/scripts/miniconda3/envs/pypeit/lib/python3.9/site-packages/pypeit/edgetrace.py", line 497, in __init__
    self.auto_trace(debug=debug, show_stages=show_stages)
  File "/Users/ckilpatrick/scripts/miniconda3/envs/pypeit/lib/python3.9/site-packages/pypeit/edgetrace.py", line 787, in auto_trace
    self.initial_trace(bpm=bpm)
  File "/Users/ckilpatrick/scripts/miniconda3/envs/pypeit/lib/python3.9/site-packages/pypeit/edgetrace.py", line 989, in initial_trace
    = trace.detect_slit_edges(_img, bpm=self.tracebpm,
  File "/Users/ckilpatrick/scripts/miniconda3/envs/pypeit/lib/python3.9/site-packages/pypeit/core/trace.py", line 117, in detect_slit_edges
    tedges = np.zeros(flux.shape, dtype=np.float)
  File "/Users/ckilpatrick/scripts/miniconda3/envs/pypeit/lib/python3.9/site-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'float'
```

Can this (and other uses of np.float) be updated to:

`tedges = np.zeros(flux.shape, dtype=np.float64)`

or something equivalent to prevent the error?  My current fix is to roll back to numpy==1.23.

**Comment by kbwestfall** [comment]
Hi @charliekilpatrick .  Apologies.  We're getting a number of users experiencing the same issue.  This should be fixed in a new version of PypeIt (1.12.0), which should hopefully be ready soon (~week-ish timescale).  In the meantime, the best solution is to revert to numpy==1.23, as you've done.  This issue is effectively a repeat of #1523 , so I'm closing it.
