### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by orenir49** [pypeit/PypeIt#1605]
Hi,

I'm running into trouble trying to install pypeit using pip.
I opened a fresh virtual environment on VS code, ran 'pip install pypeit' and this is the error I got:

        _Collecting pypeit
          Using cached pypeit-1.13.0.tar.gz (133.5 MB)
          Installing build dependencies: started
          Installing build dependencies: finished with status 'done'
          Getting requirements to build wheel: started
          Getting requirements to build wheel: finished with status 'error'
          
        × Getting requirements to build wheel did not run successfully.
          │ exit code: 1
          ╰─> [44 lines of output]
              Traceback (most recent call last):
                File "C:\Users\ASUS\code\spectrum\VENV\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
                  main()
                File "C:\Users\ASUS\code\spectrum\VENV\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
                  json_out['return_val'] = hook(**hook_input['kwargs'])
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                File "C:\Users\ASUS\code\spectrum\VENV\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel   
                  return hook(config_settings)
                         ^^^^^^^^^^^^^^^^^^^^^
                File "C:\Users\ASUS\AppData\Local\Temp\pip-build-env-4wt75500\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_wheel
                  return self._get_build_requires(config_settings, requirements=['wheel'])
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                File "C:\Users\ASUS\AppData\Local\Temp\pip-build-env-4wt75500\overlay\Lib\site-packages\setuptools\build_meta.py", line 323, in _get_build_requires
                  self.run_setup()
                File "C:\Users\ASUS\AppData\Local\Temp\pip-build-env-4wt75500\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
                  exec(code, locals())
                File "<string>", line 63, in <module>
                File "C:\Users\ASUS\AppData\Local\Temp\pip-build-env-4wt75500\overlay\Lib\site-packages\extension_helpers\_setup_helpers.py", line 63, in get_extensions      
                  for setuppkg in iter_setup_packages(srcdir, packages):
                File "C:\Users\ASUS\AppData\Local\Temp\pip-build-env-4wt75500\overlay\Lib\site-packages\extension_helpers\_setup_helpers.py", line 124, in iter_setup_packages          module = import_file(setup_package,
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
                File "C:\Users\ASUS\AppData\Local\Temp\pip-build-env-4wt75500\overlay\Lib\site-packages\extension_helpers\_utils.py", line 136, in import_file
                  mod = loader.load_module()
                        ^^^^^^^^^^^^^^^^^^^^
                File "<frozen importlib._bootstrap_external>", line 605, in _check_name_wrapper
                File "<frozen importlib._bootstrap_external>", line 1120, in load_module
                File "<frozen importlib._bootstrap_external>", line 945, in load_module
                File "<frozen importlib._bootstrap>", line 290, in _load_module_shim
                File "<frozen importlib._bootstrap>", line 721, in _load
                File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
                File "<frozen importlib._bootstrap_external>", line 940, in exec_module
                File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
                File ".\pypeit\bspline\setup_package.py", line 58, in <module>
                File ".\pypeit\bspline\setup_package.py", line 36, in check_for_openmp
                File "C:\Users\ASUS\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 389, in call
                  with Popen(*popenargs, **kwargs) as p:
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
                File "C:\Users\ASUS\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1024, in __init__
                  self._execute_child(args, executable, preexec_fn, close_fds,
                File "C:\Users\ASUS\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1509, in _execute_child
                  hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              FileNotFoundError: [WinError 2] The system cannot find the file specified
              [end of output]
        
        note: This error originates from a subprocess, and is likely not a problem with pip.
        error: subprocess-exited-with-error
        
        × Getting requirements to build wheel did not run successfully.
        │ exit code: 1
        ╰─> See above for output._

I followed most of the instructions on this [post](https://bobbyhadz.com/blog/python-pip-install-failed-building-wheel-for), with no change. I hadn't found any similar issues on this thread.

Any suggestions will be greatly appreciated,
Oren

**Comment by kbwestfall** [comment]
Hi Oren,  We recently made some modest changes to the installation dependencies for version 1.13.0.  Can you provide your OS?  Do you get the same error if you try to pip install pypeit version 1.12.2?

**Comment by orenir49** [comment]
Hi Kyle,
Just tried installing version ~=1.12; seems to give the same error. 
I'm working on windows 10, could that be the problem?

**Comment by kbwestfall** [comment]
Hi Oren, I asked @tepickering , and he thinks you're missing a compiler.  We run continuous-integration tests on windows, so it should be possible to install there.  Given that you get the same error with version 1.12, I doubt this error is due to our recent changes.  Not many of us use windows, so it will be hard to debug.  But I would first make sure your environment has access to a C compiler.

**Comment by orenir49** [comment]
Tried again after installing a new C compiler- sadly still getting this error.
Anything else I could try?

Thanks for your patience,
Oren

**Comment by orenir49** [comment]
I ended up using Window Subsystem for Linux, and the issue is resolved.
Thanks for the help!

**Comment by kbwestfall** [comment]
I'm glad that you found a solution, Oren!

**Comment by tripleee** [comment]
The function which fails is trying to run a C compiler, so I guess you didn't have one on the Windows side.
