### ISSUE TITLE
bug in slitspatnum implementation

### ISSUE THREAD

**Issue by jhennawi** [pypeit/PypeIt#1643]
The following dev-suite PypeIt file crashes if you uncomment the slitspatnum field: 

gemini_gmos_gn_ham_r400_885.pypeit 

See the updated version on the sensfunc_blaze_jwst_lists dev-suite branch.  Also, we have two different names for very similar parameters, i.e. slitspatnum here and only_slits for coadd2d. Probably we should try to adopt a more consistent naming convention. 

`Traceback (most recent call last):
  File "/Users/joe/miniconda3/envs/pypeit/bin/run_pypeit", line 33, in <module>
    sys.exit(load_entry_point('pypeit', 'console_scripts', 'run_pypeit')())
  File "/Users/joe/python/PypeIt/pypeit/scripts/scriptbase.py", line 113, in entry_point
    cls.main(cls.parse_args())
  File "/Users/joe/python/PypeIt/pypeit/scripts/run_pypeit.py", line 105, in main
    pypeIt.reduce_all()
  File "/Users/joe/python/PypeIt/pypeit/pypeit.py", line 425, in reduce_all
    sci_spec2d, sci_sobjs = self.reduce_exposure(frames, bg_frames=bg_frames,
  File "/Users/joe/python/PypeIt/pypeit/pypeit.py", line 559, in reduce_exposure
    self.caliBrate = self.calib_one(frames, self.det)
  File "/Users/joe/python/PypeIt/pypeit/pypeit.py", line 698, in calib_one
    caliBrate.run_the_steps()
  File "/Users/joe/python/PypeIt/pypeit/calibrations.py", line 932, in run_the_steps
    getattr(self, f'get_{step}')()
  File "/Users/joe/python/PypeIt/pypeit/calibrations.py", line 863, in get_wv_calib
    self.wv_calib = waveCalib.run(skip_QA=(not self.write_qa),
  File "/Users/joe/python/PypeIt/pypeit/wavecalib.py", line 931, in run
    self.wv_calib = self.build_wv_calib(
  File "/Users/joe/python/PypeIt/pypeit/wavecalib.py", line 612, in build_wv_calib
    arcfitter = autoid.HolyGrail(arccen, self.lamps, par=self.par, ok_mask=ok_mask_idx,
  File "/Users/joe/python/PypeIt/pypeit/core/wavecal/autoid.py", line 1657, in __init__
    self.run_brute()
  File "/Users/joe/python/PypeIt/pypeit/core/wavecal/autoid.py", line 1785, in run_brute
    bad_slits = self.cross_match(good_fit,self._det_weak)
  File "/Users/joe/python/PypeIt/pypeit/core/wavecal/autoid.py", line 1998, in cross_match
    shift_val[cntr], ccorr_val[cntr]= wvutils.xcorr_shift(self._spec[:, sort_idx[gd]],self._spec[:, sort_idx[gc]],
  File "/Users/joe/python/PypeIt/pypeit/core/wavecal/wvutils.py", line 554, in xcorr_shift
    nspec = y1.shape[0]
`

**Comment by debora-pe** [comment]
fixed in #1645. Closing.
