### ISSUE TITLE
lt_xspec not working due to QApplication error

### ISSUE THREAD

**Issue by klaudhub** [pypeit/PypeIt#1774]
Trying to open 1D spectra (`pypeit version 1.15.0` installed via `pip`) with the `lt_xspec` command raises the following issue: 
```
File "/home/user/anaconda3/envs/pypeit/bin/lt_xspec", line 8, in <module>
    sys.exit(main())
             ^^^^^^
File "/home/user/anaconda3/envs/pypeit/lib/python3.11/site-packages/linetools/scripts/lt_xspec.py", line 84, in main
    width = app.desktop().screenGeometry().width()
            ^^^^^^^^^^^
AttributeError: 'QApplication' object has no attribute 'desktop'
```
Since `QApplication` is drawn from `qtpy.QtWidgets`, the issue might be solved by rolling back from the `qtpy version 2.4.1`, but I am not entirely sure. Thanks!

**Comment by seib2** [comment]
I can confirm this issue on a fresh conda environment and the current pip version of pypeit. pypeit_show_1dspec fails due to a related QT error:

```
> pypeit_show_1dspec spec1d_DE.20220225.19412-DE.20220225.42197-J0910_mask1.fits 
 RequestsDependencyWarning: urllib3 (2.2.1) or chardet (3.0.4) doesn't match a supported version! (__init__.py:89)
Traceback (most recent call last):
  File "/home/sarah/.local/bin/pypeit_show_1dspec", line 8, in <module>
    sys.exit(Show1DSpec.entry_point())
  File "/home/sarah/.local/lib/python3.8/site-packages/pypeit/scripts/scriptbase.py", line 112, in entry_point
    cls.main(cls.parse_args())
  File "/home/sarah/.local/lib/python3.8/site-packages/pypeit/scripts/show_1dspec.py", line 41, in main
    from qtpy.QtWidgets import QApplication
  File "/home/sarah/.local/lib/python3.8/site-packages/qtpy/__init__.py", line 287, in <module>
    raise QtBindingsNotFoundError from None
qtpy.QtBindingsNotFoundError: No Qt bindings could be found

**Comment by freddavies** [comment]
The solution to the lt_xspec issue seems to be replacing the offending line in `linetools/scripts/lt_xspec.py`  with the new (QT6?) version from pypeit_show_1dspec,

old:
`width = app.desktop().screenGeometry().width()`
new:
`width = app.screens()[0].geometry().width()`

Perhaps a small linetools PR?
