### ISSUE TITLE
Deprecate `pypeit_install_ql_calibs`

### ISSUE THREAD

**Issue by kbwestfall** [pypeit/PypeIt#1786]
Is this script still needed / useful?

**Comment by Hellseher** [comment]
Hi,

While packaging pypeit@1.17.4 for Guix and it has that script missed:
```
...trying to load endpoint console_scripts pypeit_install_ql_calibs: ERROR:
Traceback (most recent call last):
  File "/gnu/store/iqsjkp55pcx5bfcp2jm9yj5rlx9a0whd-sanity-check.py", line 89, in <module>
    ep.load()
  File "/gnu/store/ym4hd0kk40y4fq6m8balv2bamfc2kib0-python-setuptools-80.9.0/lib/python3.11/site-packages/pkg_resources/__init__.py", line 2777, in load
    return self.resolve()
           ^^^^^^^^^^^^^^
  File "/gnu/store/ym4hd0kk40y4fq6m8balv2bamfc2kib0-python-setuptools-80.9.0/lib/python3.11/site-packages/pkg_resources/__init__.py", line 2783, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'pypeit.scripts.install_ql_calib'
...trying to load endpoint console_scripts pypeit_install_telluric: OK
...trying to load endpoint console_scripts pypeit_install_wvarxiv: OK
...trying to load endpoint console_scripts pypeit_lowrdx_skyspec: OK
...trying to load endpoint console_scripts pypeit_multislit_flexure: OK
...trying to load endpoint console_scripts pypeit_obslog: OK
...trying to load endpoint console_scripts pypeit_parse_slits: OK
...trying to load endpoint console_scripts pypeit_print_bpm: OK
...trying to load endpoint console_scripts pypeit_qa_html: OK
...trying to load endpoint console_scripts pypeit_ql: OK
...trying to load endpoint console_scripts pypeit_ql_multislit: ERROR:
Traceback (most recent call last):
  File "/gnu/store/iqsjkp55pcx5bfcp2jm9yj5rlx9a0whd-sanity-check.py", line 89, in <module>
    ep.load()
  File "/gnu/store/ym4hd0kk40y4fq6m8balv2bamfc2kib0-python-setuptools-80.9.0/lib/python3.11/site-packages/pkg_resources/__init__.py", line 2777, in load
    return self.resolve()
           ^^^^^^^^^^^^^^
  File "/gnu/store/ym4hd0kk40y4fq6m8balv2bamfc2kib0-python-setuptools-80.9.0/lib/python3.11/site-packages/pkg_resources/__init__.py", line 2783, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'pypeit.scripts.ql_multislit'
```
