### ISSUE TITLE
All DEIMOS setups are failing in the test suite

### ISSUE THREAD

**Issue by jhennawi** [pypeit/PypeIt#456]
The crash is in core/wavecal/autoid.py

for both multislit and longslit 

Is this a result of fixes to arclines @rcooke-ast? Did you run the test suite for DEIMOS? 

If yes, then I don't understand why these codes are so unstable. 

Traceback (most recent call last):
  File "/Users/joe/anaconda3/bin//run_pypeit", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/joe/python/PypeIt/bin/run_pypeit", line 17, in <module>
    rtval = run_pypeit.main(args)
  File "/Users/joe/python/PypeIt/pypeit/scripts/run_pypeit.py", line 85, in main
    verbosity=args.verbosity, use_masters=args.use_masters, logname=logname)
  File "/Users/joe/python/PypeIt/pypeit/pypeit.py", line 115, in PypeIt
    status = arms.ARMS(fitstbl, setup_dict, par=par, spectrograph=spectrograph)
  File "/Users/joe/python/PypeIt/pypeit/arms.py", line 142, in ARMS
    wv_calib, maskslits = caliBrate.get_wv_calib()
  File "/Users/joe/python/PypeIt/pypeit/calibrations.py", line 574, in get_wv_calib
    nonlinear=nonlinear, skip_QA=(~self.write_qa))
  File "/Users/joe/python/PypeIt/pypeit/wavecalib.py", line 334, in run
    self.wv_calib = self._build_wv_calib(self.par['method'], skip_QA=skip_QA)
  File "/Users/joe/python/PypeIt/pypeit/wavecalib.py", line 140, in _build_wv_calib
    self.wv_calib = arc.calib_with_arclines(self.arcparam, self.arccen, ok_mask=ok_mask)
  File "/Users/joe/python/PypeIt/pypeit/core/arc.py", line 541, in calib_with_arclines
    fit_parm=aparm, min_ampl=aparm['min_ampl'])
  File "/Users/joe/python/PypeIt/pypeit/core/wavecal/autoid.py", line 624, in general
    aparm=fit_parm)
  File "/Users/joe/python/PypeIt/pypeit/core/wavecal/fitting.py", line 40, in iterative_fitting
    mask, fit = utils.robust_polyfit(xfit, yfit, n_order, function=aparm['func'], sigma=aparm['nsig_rej'], minv=fmin, maxv=fmax)
  File "/Users/joe/python/PypeIt/pypeit/utils.py", line 954, in robust_polyfit
    guesses=ct, minv=minv, maxv=maxv, bspline_par=bspline_par)
  File "/Users/joe/python/PypeIt/pypeit/utils.py", line 364, in func_fit
    return np.polynomial.legendre.legfit(xv, y, deg, w=w)
  File "/Users/joe/anaconda3/lib/python3.6/site-packages/numpy/polynomial/legendre.py", line 1530, in legfit
    raise TypeError("expected non-empty vector for x")
TypeError: expected non-empty vector for x

**Comment by rcooke-ast** [comment]
Solved by PR #460
