### ISSUE TITLE
No Raw Data

### ISSUE THREAD

**Issue by ChrisRsk** [pypeit/PypeIt#525]
Hello I am attempting to use Pypelt to reduce some LRIS blue data that I have, but I'm running into some issues. I am running on macOS High Sierra version 10.13.6 operating system, and I have the following versions of the required dependencies:
-python 3.7
-numpy 1.15.2
-Astropy 3.0.4
-Scipy 1.1
-matplotlib 3.0
-numba 0.39.0
-pyqt 5.9.2
-h5py 2.8
-yaml 0.1.7
-future 0.16.0
-configobj 5.0.6
-ginga 2.7.2
I have identified the path to my raw data (includes .spyder-py3, but have attempted at other locations without .*) and have used pypeit_setup /full_path/RAWDIR/lrisb  keck_lris_blue but I keep getting the following error:

[ERROR]   :: util.py 454 parse_pypeit_file() - There are no raw data frames
             Perhaps the path to the data is incorrect?
Traceback (most recent call last):
  File "/anaconda3/bin/pypeit_setup", line 4, in <module>
    __import__('pkg_resources').run_script('pypeit==0.8.2.dev0', 'pypeit_setup')
  File "/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 661, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1441, in run_script
    exec(code, namespace, namespace)
  File "/anaconda3/lib/python3.7/site-packages/pypeit-0.8.2.dev0-py3.7.egg/EGG-INFO/scripts/pypeit_setup", line 17, in <module>
    setup.main(args)
  File "/anaconda3/lib/python3.7/site-packages/pypeit-0.8.2.dev0-py3.7.egg/pypeit/scripts/setup.py", line 66, in main
    pypeIt.build_setup_files(args.files_root)
  File "/anaconda3/lib/python3.7/site-packages/pypeit-0.8.2.dev0-py3.7.egg/pypeit/pypeit.py", line 105, in build_setup_files
    sort_dir=sort_dir)
  File "/anaconda3/lib/python3.7/site-packages/pypeit-0.8.2.dev0-py3.7.egg/pypeit/pypeit.py", line 622, in _setup
    self.pypeitSetup = pypeitsetup.PypeItSetup.from_pypeit_file(pypeit_file)
  File "/anaconda3/lib/python3.7/site-packages/pypeit-0.8.2.dev0-py3.7.egg/pypeit/pypeitsetup.py", line 156, in from_pypeit_file
    cfg_lines, data_files, frametype, setups = parse_pypeit_file(filename)
  File "/anaconda3/lib/python3.7/site-packages/pypeit-0.8.2.dev0-py3.7.egg/pypeit/par/util.py", line 454, in parse_pypeit_file
    'Perhaps the path to the data is incorrect?')
  File "/anaconda3/lib/python3.7/site-packages/pypeit-0.8.2.dev0-py3.7.egg/pypeit/pypmsgs.py", line 269, in error
    raise PypeItError("PYPIT ENDS")
pypeit.pypmsgs.PypeItError: PYPIT ENDS

I have been unable to find the source of the problem. I note as well that I am using .fits files, do I need to convert these files first? Thank you.

**Comment by ChrisRsk** [comment]
UPDATE:
I was able to run the program on the data. The issue was an additional backslash that was needed in the specification of the path (i.e. /Users/me/mydirectory/). When I did this program was able to find the files.
Thank you
