### ISSUE TITLE
Error with last step of X-shooter VIS reduction

### ISSUE THREAD

**Issue by keheintz** [pypeit/PypeIt#541]
I am currently trying to reduce a GRB data set with PypeIt. The UVB and VIS arm appear to run smoothly when producing the .pypeit files and running the calibration checks (so all steps to step 6 including in the cookbook). However, when I try to run the run_pypeit command I get the following traceback error (it seems to still produce master flats, arcs and traces):

Traceback (most recent call last):
  File "//anaconda/envs/py36/bin/run_pypeit", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/keheintz/PypeIt/bin/run_pypeit", line 17, in <module>
    rtval = run_pypeit.main(args)
  File "/Users/keheintz/PypeIt/pypeit/scripts/run_pypeit.py", line 108, in main
    pypeIt.reduce_all(reuse_masters=args.use_masters)
  File "/Users/keheintz/PypeIt/pypeit/pypeit.py", line 231, in reduce_all
    sci_dict = self.reduce_exposure(sci_ID, reuse_masters=reuse_masters)
  File "/Users/keheintz/PypeIt/pypeit/pypeit.py", line 347, in reduce_exposure
    self.calibrate_one(sci_ID, det)
  File "/Users/keheintz/PypeIt/pypeit/pypeit.py", line 703, in calibrate_one
    self.caliBrate.run_the_steps()
  File "/Users/keheintz/PypeIt/pypeit/calibrations.py", line 697, in run_the_steps
    getattr(self, 'get_{:s}'.format(step))()
  File "/Users/keheintz/PypeIt/pypeit/calibrations.py", line 594, in get_wv_calib
    nonlinear=nonlinear, skip_QA=(not self.write_qa))
  File "/Users/keheintz/PypeIt/pypeit/wavecalib.py", line 371, in run
    self.wv_calib = self._build_wv_calib(self.par['method'], skip_QA=skip_QA)
  File "/Users/keheintz/PypeIt/pypeit/wavecalib.py", line 183, in _build_wv_calib
    arcfitter = autoid.General(self.arccen, par = self.par, ok_mask=ok_mask)
  File "/Users/keheintz/PypeIt/pypeit/core/wavecal/autoid.py", line 400, in __init__
    if 'ThAr' in self._lines:
TypeError: argument of type 'NoneType' is not iterable

Any suggestions? Thanks in advance.

**Comment by EmAstro** [comment]
Hi, the problem is that the wavelength solution for XSHOOTER is not supported yet. So you are having a failure in wavecalib.py.

**Comment by keheintz** [comment]
Hi, thanks for your response. But alright, is there anything I can do on my side to work on this issue? From the file I can see that the ThAr lamp is simply not loaded. 
Let me know if I can be of any assistance. I'm on the team trying to modify PypeIt to also include the new NTE instrument for the NOT, which is going to be similar to X-shooter, so we would like to assist wherever possible.

**Comment by jhennawi** [comment]
Hi @keheintz, 

Send me your e-mail and I'll add you to the PypeIt Slack and you can follow the #x-shooter channel there. We are making rapid progress, but the echelle mode of pypeit is very much in beta-tester mode. 

I'd suggest installing the PypeIt-Development-Suite: https://github.com/pypeit/PypeIt-development-suite and trying out the X-shooter test data there. 

Joe

**Comment by keheintz** [comment]
Hi Joe, 
Thanks, that would be great! Please add: keh14@hi.is 
And ok, I'll install the development suite as well.
Kasper

**Comment by jhennawi** [comment]
I think this has been fixed.
