### ISSUE TITLE
Strange error when running ~10 science frames at once, LRISb 400 grism

### ISSUE THREAD

**Issue by ChrisRsk** [pypeit/PypeIt#608]
I am running the reduction on a set of LRISb data with the 400 grism and a 560 dichroic and have run into a strange error with the sky subtraction around the objects (currently with model_full_slit set to True). When I try to run the code with all 10 science frames I get the following error:

Traceback (most recent call last):
  File "/anaconda3/bin/run_pypeit", line 4, in <module>
    __import__('pkg_resources').run_script('pypeit==0.9.2.dev0', 'run_pypeit')
  File "/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 661, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1441, in run_script
    exec(code, namespace, namespace)
  File "/anaconda3/lib/python3.7/site-packages/pypeit-0.9.2.dev0-py3.7.egg/EGG-INFO/scripts/run_pypeit", line 17, in <module>
    rtval = run_pypeit.main(args)
  File "/anaconda3/lib/python3.7/site-packages/pypeit-0.9.2.dev0-py3.7.egg/pypeit/scripts/run_pypeit.py", line 99, in main
    pypeIt.reduce_all()
  File "/anaconda3/lib/python3.7/site-packages/pypeit-0.9.2.dev0-py3.7.egg/pypeit/pypeit.py", line 251, in reduce_all
    sci_dict = self.reduce_exposure(frames, bg_frames=bg_frames, std_outfile=std_outfile)
  File "/anaconda3/lib/python3.7/site-packages/pypeit-0.9.2.dev0-py3.7.egg/pypeit/pypeit.py", line 344, in reduce_exposure
    = self.extract_one(self.frames, self.det, bg_frames = self.bg_frames, std_outfile = std_outfile)
  File "/anaconda3/lib/python3.7/site-packages/pypeit-0.9.2.dev0-py3.7.egg/pypeit/pypeit.py", line 514, in extract_one
    maskslits=self.maskslits, show_profile=self.show,show=self.show)
  File "/anaconda3/lib/python3.7/site-packages/pypeit-0.9.2.dev0-py3.7.egg/pypeit/reduce.py", line 587, in local_skysub_extract
    show_resids=show_resids)
  File "/anaconda3/lib/python3.7/site-packages/pypeit-0.9.2.dev0-py3.7.egg/pypeit/core/skysub.py", line 708, in local_skysub_extract
    fullbkpt=fullbkpt, sigrej=sigrej_eff, npoly=npoly)
  File "/anaconda3/lib/python3.7/site-packages/pypeit-0.9.2.dev0-py3.7.egg/pypeit/core/skysub.py", line 251, in skyoptimal
    relative=relative,kwargs_reject={'groupbadpix': True, 'maxrej': 5})
ValueError: not enough values to unpack (expected 5, got 4)

However, when I run the same code (all parameters exactly the same in the pypeit file) on the same science frame (running on just that science frame and no others) for which the code crashed it runs through without error. I can only imagine that there is some cross-correlation with previous science frames? but I cannot pin point exactly what's happening here. Additionally, I have limited the number of objects to 2 per slit (however, this same error occurs without this restriction)

**Comment by profxj** [comment]
@ChrisRsk -- Is this still an Issue?

**Comment by csnap001** [comment]
(Original poster, new profile) It seems to be a consequence of the shift in the pixel position of objects throughout the science frames and is avoided by running the code in groups of science frames without a shift between them. In short, no this is no longer an issue. My apologies.
