### ISSUE TITLE
DEIMOS_600ZD_7500 failing in flexure

### ISSUE THREAD

**Issue by jhennawi** [pypeit/PypeIt#631]
Here is the traceback in flexure. Looks like the something is wrong with the wavelength coverage of the archival sky spectrum. 

ESC[1;31m[WARNING] ::ESC[0m ESC[1;34mwave.py 321 flexure_obj()ESC[0m - No previous good solution.  Punting on this object
Traceback (most recent call last):
  File "/Users/joe/anaconda3/bin/run_pypeit", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/Users/joe/python/PypeIt/bin/run_pypeit", line 17, in <module>
    rtval = run_pypeit.main(args)
  File "/Users/joe/python/PypeIt/pypeit/scripts/run_pypeit.py", line 99, in main
    pypeIt.reduce_all()
  File "/Users/joe/python/PypeIt/pypeit/pypeit.py", line 265, in reduce_all
    sci_dict = self.reduce_exposure(frames, bg_frames=bg_frames, std_outfile=std_outfile)
  File "/Users/joe/python/PypeIt/pypeit/pypeit.py", line 358, in reduce_exposure
    = self.extract_one(self.frames, self.det, bg_frames = self.bg_frames, std_outfile = std_outfile)
  File "/Users/joe/python/PypeIt/pypeit/pypeit.py", line 585, in extract_one
    self.redux.flexure_correct(self.sobjs, self.basename)
  File "/Users/joe/python/PypeIt/pypeit/reduce.py", line 357, in flexure_correct
    wave.flexure_qa(sobjs, self.maskslits, basename, self.det, flex_list,out_dir=self.par['rdx']['redux_path'])
  File "/Users/joe/python/PypeIt/pypeit/core/wave.py", line 650, in flexure_qa
    fit = this_flex_dict['polyfit'][iobj]
IndexError: list index out of range

**Comment by profxj** [comment]
No longer the case, I think.
