### ISSUE TITLE
Opaque bail-out when bias frame not included

### ISSUE THREAD

**Issue by AlexaVillaume** [pypeit/PypeIt#650]
Without additional changes to the pypeit file, if a bias frame is not included in the reduction, run_pypeit will fail and give a unclear error message:

> (py36) eduroam-169-233-187-211:PYPIT_Test alexa$ run_pypeit keck_lris_blue_B/keck_lris_blue_B.pypeit -o
[INFO]    :: Loading the reduction file
[INFO]    :: Found 3 raw data frames
[INFO]    :: Input file loaded successfully
[INFO]    :: Loading the reduction file
[INFO]    :: Found 3 raw data frames
[INFO]    :: Input file loaded successfully
[WARNING] :: Removing existing frametype and framebit columns.
[INFO]    :: Typing files
[INFO]    :: Using user-provided frame types.
[INFO]    :: Setting reduction path to /Users/alexa/Documents/PYPIT_Test
[INFO]    :: Creating Science directory
[INFO]    :: The following directory already exists:
             /Users/alexa/Documents/PYPIT_Test/Science
[INFO]    :: Creating Object directories
[INFO]    :: Creating Master Calibrations directory
[INFO]    :: The following directory already exists:
             /Users/alexa/Documents/PYPIT_Test/MF_keck_lris_blue
[INFO]    :: Creating QA directory
[WARNING] :: Pre-existing QA plots will be overwritten
[INFO]    :: Reducing target B225-G280
             Combining frames:
             b161027_0050.fits
[INFO]    :: Working on detector 1
[INFO]    :: Reading LRIS file: /Users/alexa/Documents/PYPIT_Test/b161027_0050.fits
[INFO]    :: Reading LRIS file: /Users/alexa/Documents/PYPIT_Test/b161027_0050.fits
[INFO]    :: Using hard-coded BPM for det=1 on LRISb
[WARNING] :: Your images have not been bias subtracted!
Traceback (most recent call last):
  File "/Users/alexa/anaconda/envs/py36/bin/run_pypeit", line 17, in <module>
    rtval = run_pypeit.main(args)
  File "/Users/alexa/anaconda/envs/py36/lib/python3.6/site-packages/pypeit/scripts/run_pypeit.py", line 99, in main
    pypeIt.reduce_all()
  File "/Users/alexa/anaconda/envs/py36/lib/python3.6/site-packages/pypeit/pypeit.py", line 265, in reduce_all
    sci_dict = self.reduce_exposure(frames, bg_frames=bg_frames, std_outfile=std_outfile)
  File "/Users/alexa/anaconda/envs/py36/lib/python3.6/site-packages/pypeit/pypeit.py", line 350, in reduce_exposure
    self.caliBrate.run_the_steps()
  File "/Users/alexa/anaconda/envs/py36/lib/python3.6/site-packages/pypeit/calibrations.py", line 763, in run_the_steps
    getattr(self, 'get_{:s}'.format(step))()
  File "/Users/alexa/anaconda/envs/py36/lib/python3.6/site-packages/pypeit/calibrations.py", line 293, in get_bias
    self.msbias = self.biasFrame.build_image()
  File "/Users/alexa/anaconda/envs/py36/lib/python3.6/site-packages/pypeit/biasframe.py", line 79, in build_image
    self.stack = self.process(bias_subtract=None, trim=trim, overwrite=overwrite)
  File "/Users/alexa/anaconda/envs/py36/lib/python3.6/site-packages/pypeit/processimages.py", line 543, in process
    temp = self.raw_images[0]

**Comment by profxj** [comment]
Addressed by #700
