### ISSUE TITLE
Manual extraction not working on multi-slit data

### ISSUE THREAD

**Issue by freddavies** [pypeit/PypeIt#661]
Already discussed a bit on Slack, but adding an issue here for posterity. 

When I try to manually extract objects on a multi-slit DEIMOS data set (via the `manual_extract` column in the .pypeit file), it crashes, seemingly because it’s confused that there are no objects in the first slit:
```
[INFO]    :: Finding objects on slit # 0
[WARNING] :: Requested nperslit = 10 most significant objects but only npeak = 5 were found. Returning all the objects found.
[INFO]    :: Used SIGNIFICANCE threshold: sig_thresh = 10.0 * sigma =  0.17
[INFO]    :: Object finding threshold of:  1.66
[INFO]    :: Fitting the object traces
Traceback (most recent call last):
  File "/Users/fdavies/anaconda/bin/run_pypeit", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/Users/fdavies/PypeIt/bin/run_pypeit", line 17, in <module>
    rtval = run_pypeit.main(args)
  File "/Users/fdavies/PypeIt/pypeit/scripts/run_pypeit.py", line 99, in main
    pypeIt.reduce_all()
  File "/Users/fdavies/PypeIt/pypeit/pypeit.py", line 265, in reduce_all
    sci_dict = self.reduce_exposure(frames, bg_frames=bg_frames, std_outfile=std_outfile)
  File "/Users/fdavies/PypeIt/pypeit/pypeit.py", line 358, in reduce_exposure
    = self.extract_one(self.frames, self.det, bg_frames = self.bg_frames, std_outfile = std_outfile)
  File "/Users/fdavies/PypeIt/pypeit/pypeit.py", line 551, in extract_one
    manual_extract_dict=manual_extract_dict)
  File "/Users/fdavies/PypeIt/pypeit/reduce.py", line 208, in find_objects
    manual_extract_dict=parse_manual)
  File "/Users/fdavies/PypeIt/pypeit/reduce.py", line 596, in find_objects_pypeline
    qa_title=qa_title, nperslit=self.redux_par['maxnumber'])
  File "/Users/fdavies/PypeIt/pypeit/core/extract.py", line 1817, in objfind
    spat_pixpos = sobjs.spat_pixpos
  File "/Users/fdavies/PypeIt/pypeit/specobjs.py", line 566, in __getattr__
    raise ValueError("Attribute not available!")
ValueError: Attribute not available!
```

For reference, if I do not specify any manual extraction locations, I get the following messages and PypeIt continues on to the next slit:
```
[INFO]    :: Finding objects on slit # 0
[WARNING] :: Requested nperslit = 10 most significant objects but only npeak = 5 were found. Returning all the objects found.
[INFO]    :: Used SIGNIFICANCE threshold: sig_thresh = 10.0 * sigma =  0.17
[INFO]    :: Object finding threshold of:  1.66
[INFO]    :: No objects found
```

**Comment by profxj** [comment]
implemented
