### ISSUE TITLE
Overscan crash in LRISr

### ISSUE THREAD

**Issue by profxj** [pypeit/PypeIt#664]
Dang amplifier non-sense yet again..

[ERROR]   :: procimg.py 582 subtract_overscan() - Overscan sections do not match amplifier sections foramplifier 1
Traceback (most recent call last):
  File "/home/xavier/.pyenv/versions/anaconda3-5.2.0/bin/run_pypeit", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/data/Projects/Python/PypeIt/bin/run_pypeit", line 17, in <module>
    rtval = run_pypeit.main(args)
  File "/data/Projects/Python/PypeIt/pypeit/scripts/run_pypeit.py", line 99, in main
    pypeIt.reduce_all()
  File "/data/Projects/Python/PypeIt/pypeit/pypeit.py", line 265, in reduce_all
    sci_dict = self.reduce_exposure(frames, bg_frames=bg_frames, std_outfile=std_outfile)
  File "/data/Projects/Python/PypeIt/pypeit/pypeit.py", line 350, in reduce_exposure
    self.caliBrate.run_the_steps()
  File "/data/Projects/Python/PypeIt/pypeit/calibrations.py", line 763, in run_the_steps
    getattr(self, 'get_{:s}'.format(step))()
  File "/data/Projects/Python/PypeIt/pypeit/calibrations.py", line 239, in get_arc
    self.msarc = self.arcImage.build_image()
  File "/data/Projects/Python/PypeIt/pypeit/arcimage.py", line 76, in build_image
    self.stack = self.process(bias_subtract=self.msbias, overwrite=overwrite, trim=True)
  File "/data/Projects/Python/PypeIt/pypeit/processimages.py", line 535, in process
    self.bias_subtract(bias_subtract, trim=trim)
  File "/data/Projects/Python/PypeIt/pypeit/processimages.py", line 428, in bias_subtract
    params=self.proc_par['overscan_par'])
  File "/data/Projects/Python/PypeIt/pypeit/core/procimg.py", line 582, in subtract_overscan
    'amplifier {0}'.format(i+1))
  File "/data/Projects/Python/PypeIt/pypeit/pypmsgs.py", line 269, in error
    raise PypeItError(msg)
pypeit.pypmsgs.PypeItError: Overscan sections do not match amplifier sections foramplifier 1

**Comment by profxj** [comment]
Addressed by #672
