### ISSUE TITLE
Arc tilt crash in LRISr 400/8500

### ISSUE THREAD

**Issue by profxj** [pypeit/PypeIt#665]
I suspect a bad slit up-stream..

[INFO]    :: wavetilts.py 295 run() - Computing tilts for slit 0/10
[WARNING] :: tracewave.py 77 tilts_find_lines() - No arc lines were deemed usable on this slit. Cannot compute tilts. Try lowering tracethresh.
Traceback (most recent call last):
  File "/home/xavier/.pyenv/versions/anaconda3-5.2.0/bin/run_pypeit", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/data/Projects/Python/PypeIt/bin/run_pypeit", line 17, in <module>
    rtval = run_pypeit.main(args)
  File "/data/Projects/Python/PypeIt/pypeit/scripts/run_pypeit.py", line 99, in main
    pypeIt.reduce_all()
  File "/data/Projects/Python/PypeIt/pypeit/pypeit.py", line 265, in reduce_all
    sci_dict = self.reduce_exposure(frames, bg_frames=bg_frames, std_outfile=std_outfile)
  File "/data/Projects/Python/PypeIt/pypeit/pypeit.py", line 350, in reduce_exposure
    self.caliBrate.run_the_steps()
  File "/data/Projects/Python/PypeIt/pypeit/calibrations.py", line 763, in run_the_steps
    getattr(self, 'get_{:s}'.format(step))()
  File "/data/Projects/Python/PypeIt/pypeit/calibrations.py", line 746, in get_tilts
    = self.waveTilts.run(maskslits=self.maskslits,doqa=self.write_qa, show=self.show)
  File "/data/Projects/Python/PypeIt/pypeit/wavetilts.py", line 297, in run
    self.lines_spec, self.lines_spat = self.find_lines(self.arccen[:,slit], self.slitcen[:,slit], slit, debug=debug)
  File "/data/Projects/Python/PypeIt/pypeit/wavetilts.py", line 165, in find_lines
    nonlinear_counts=self.nonlinear_counts, debug_peaks=False, debug_lines = debug)
TypeError: 'NoneType' object is not iterable

**Comment by profxj** [comment]
Indeed a bad slit, but `tracewave.tilts_find_lines()` had a bug
on the `return`

**Comment by profxj** [comment]
Addressed by #672
