### ISSUE TITLE
Flat fielding a bad slit

### ISSUE THREAD

**Issue by profxj** [pypeit/PypeIt#666]
Apparently the flat fielding ignores whether a slit is bad or not.
Or maybe the mask isn't propagating correctly.  

Investigating..

[INFO]    :: flatfield.py 222 run() - Computing flat field image for slit: 0/10
[INFO]    :: flat.py 237 fit_flat() - Spectral fit of flatfield for 115559 pixels
[INFO]    :: utils.py 393 bspline_profile() - Fitting npoly =  1 profile basis functions, nin=115559 good pixels
[INFO]    :: utils.py 394 bspline_profile() - ******************************  Iter  Chi^2  # rejected  Rel. fact   ******************************
[INFO]    :: utils.py 395 bspline_profile() -                               ----  -----  ----------  --------- 
[WARNING] :: pydl.py 877 cholesky_band() - NaN found in cholesky_band.
[WARNING] :: pydl.py 710 maskpoints() - Fewer good break points than order of b-spline. Returning...
[WARNING] :: utils.py 448 bspline_profile() -  All break points have been dropped!! Fit failed, I hope you know what you are doing
Traceback (most recent call last):
  File "/home/xavier/.pyenv/versions/anaconda3-5.2.0/bin/run_pypeit", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/data/Projects/Python/PypeIt/bin/run_pypeit", line 17, in <module>
    rtval = run_pypeit.main(args)
  File "/data/Projects/Python/PypeIt/pypeit/scripts/run_pypeit.py", line 99, in main
    pypeIt.reduce_all()
  File "/data/Projects/Python/PypeIt/pypeit/pypeit.py", line 265, in reduce_all
    sci_dict = self.reduce_exposure(frames, bg_frames=bg_frames, std_outfile=std_outfile)
  File "/data/Projects/Python/PypeIt/pypeit/pypeit.py", line 350, in reduce_exposure
    self.caliBrate.run_the_steps()
  File "/data/Projects/Python/PypeIt/pypeit/calibrations.py", line 763, in run_the_steps
    getattr(self, 'get_{:s}'.format(step))()
  File "/data/Projects/Python/PypeIt/pypeit/calibrations.py", line 437, in get_flats
    self.mspixflatnrm, self.msillumflat = self.flatField.run(show=self.show)
  File "/data/Projects/Python/PypeIt/pypeit/flatfield.py", line 241, in run
    tweak_slits_maxfrac=self.flatpar['tweak_slits_maxfrac'],debug=debug)
  File "/data/Projects/Python/PypeIt/pypeit/core/flat.py", line 303, in fit_flat
    bsp_set = pydl.bspline(ximg_fit,nord=4, bkspace=ximg_bsp)
  File "/data/Projects/Python/PypeIt/pypeit/core/pydl.py", line 268, in __init__
    startx = x.min()
  File "/home/xavier/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/site-packages/numpy/core/_methods.py", line 32, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial)
ValueError: zero-size array to reduction operation minimum which has no identity
profx>

**Comment by profxj** [comment]
Addressed by #672
