### ISSUE TITLE
LRISr longonly overscan

### ISSUE THREAD

**Issue by profxj** [pypeit/PypeIt#675]
Crashing out on overscan subtraction

**Comment by abostroem** [comment]
Here's the traceback
```
$ run_pypeit keck_lris_red_longonly_A/keck_lris_red_longonly_A.pypeit -o
[INFO]    :: Loading the reduction file
[INFO]    :: Found 8 raw data frames
[INFO]    :: Input file loaded successfully
[INFO]    :: Loaded spectrograph keck_lris_red_longonly
[INFO]    :: Setting configuration-specific parameters using r190205_0002.fits
[INFO]    :: Built full PypeIt parameter set.
[INFO]    :: Compiling metadata
[INFO]    :: Added metadata for r190205_0021.fits
[INFO]    :: Added metadata for r190205_0022.fits
[INFO]    :: Added metadata for r190205_0023.fits
[INFO]    :: Added metadata for r190205_0024.fits
[INFO]    :: Added metadata for r190205_0025.fits
[INFO]    :: Added metadata for r190205_0001.fits
[INFO]    :: Added metadata for r190205_0002.fits
[INFO]    :: Added metadata for r190205_0027.fits
[WARNING] :: Removing existing frametype and framebit columns.
[INFO]    :: Typing files
[INFO]    :: Using user-provided frame types.
[INFO]    :: Setting reduction path to /Users/bostroem/Desktop/PypeIt
[INFO]    :: Master calibration data output to: /Users/bostroem/Desktop/PypeIt/Masters
[INFO]    :: Science data output to: /Users/bostroem/Desktop/PypeIt/Science
[INFO]    :: Quality assessment plots output to: /Users/bostroem/Desktop/PypeIt/QA
[INFO]    :: Reducing target G191B2B
             Combining frames:
             r190205_0001.fits
             
[INFO]    :: Working on detector 1
[WARNING] :: Unexpected size for LRIS detector.  We expect you did some windowing...
[WARNING] :: PypeIt will not reuse masters!
[INFO]    :: Preparing a master arc frame
[WARNING] :: Unexpected size for LRIS detector.  We expect you did some windowing...
[WARNING] :: Unexpected size for LRIS detector.  We expect you did some windowing...
[INFO]    :: Bias subtracting your image(s)
[INFO]    :: Using overscan to subtract

[ERROR]   :: Overscan sections do not match amplifier sections foramplifier 1
Traceback (most recent call last):
  File "/Users/bostroem/anaconda/envs/py37/bin/run_pypeit", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/Users/bostroem/Desktop/research/not_my_code/PypeIt/bin/run_pypeit", line 17, in <module>
    rtval = run_pypeit.main(args)
  File "/Users/bostroem/Desktop/research/not_my_code/PypeIt/pypeit/scripts/run_pypeit.py", line 95, in main
    pypeIt.reduce_all()
  File "/Users/bostroem/Desktop/research/not_my_code/PypeIt/pypeit/pypeit.py", line 270, in reduce_all
    std_dict = self.reduce_exposure(frames, bg_frames=bg_frames)
  File "/Users/bostroem/Desktop/research/not_my_code/PypeIt/pypeit/pypeit.py", line 404, in reduce_exposure
    self.caliBrate.run_the_steps()
  File "/Users/bostroem/Desktop/research/not_my_code/PypeIt/pypeit/calibrations.py", line 836, in run_the_steps
    getattr(self, 'get_{:s}'.format(step))()
  File "/Users/bostroem/Desktop/research/not_my_code/PypeIt/pypeit/calibrations.py", line 309, in get_arc
    self.msarc = self.arcImage.build_image()
  File "/Users/bostroem/Desktop/research/not_my_code/PypeIt/pypeit/arcimage.py", line 82, in build_image
    return self.process(bias_subtract=self.msbias, overwrite=overwrite, trim=True)
  File "/Users/bostroem/Desktop/research/not_my_code/PypeIt/pypeit/processimages.py", line 530, in process
    self.bias_subtract(bias_subtract, trim=trim)
  File "/Users/bostroem/Desktop/research/not_my_code/PypeIt/pypeit/processimages.py", line 425, in bias_subtract
    params=self.proc_par['overscan_par'])
  File "/Users/bostroem/Desktop/research/not_my_code/PypeIt/pypeit/core/procimg.py", line 580, in subtract_overscan
    'amplifier {0}'.format(i+1))
  File "/Users/bostroem/Desktop/research/not_my_code/PypeIt/pypeit/pypmsgs.py", line 264, in error
    raise PypeItError(msg)
pypeit.pypmsgs.PypeItError: Overscan sections do not match amplifier sections foramplifier 1
```

**Comment by csnap001** [comment]
This issue seems to extend beyond long slit reductions. I'm reducing multislit data for LRIS red with 560 dichroic and 400 grism with the following traceback:

christophers-MacBook-Pro:keck_lris_red_A chrismac$ run_pypeit keck_lris_red_A.pypeit 
[INFO]    :: Loading the reduction file
[INFO]    :: Found 14 raw data frames
[INFO]    :: Input file loaded successfully
[INFO]    :: Loading the reduction file
[INFO]    :: Found 14 raw data frames
[INFO]    :: Input file loaded successfully
[WARNING] :: Removing existing frametype and framebit columns.
[INFO]    :: Typing files
[INFO]    :: Using user-provided frame types.
[INFO]    :: Setting reduction path to /Users/chrismac/Work_UCR/Brian_Data_Reduc/PypeIt_run_files/Feb_2012/Red/Abell1689/keck_lris_red_A
[INFO]    :: Creating Science directory
[INFO]    :: The following directory already exists:
             /Users/chrismac/Work_UCR/Brian_Data_Reduc/PypeIt_run_files/Feb_2012/Red/Abell1689/keck_lris_red_A/Science
[INFO]    :: Creating Object directories
[INFO]    :: Creating Master Calibrations directory
[INFO]    :: The following directory already exists:
             /Users/chrismac/Work_UCR/Brian_Data_Reduc/PypeIt_run_files/Feb_2012/Red/Abell1689/keck_lris_red_A/MF_keck_lris_red
[INFO]    :: Creating QA directory
[WARNING] :: Pre-existing QA plots will be overwritten
[INFO]    :: Reducing target a1689_3
             Combining frames:
             r120223_0045.fits
             
[WARNING] :: Not reducing detectors: 0 1
[INFO]    :: Working on detector 2
[INFO]    :: Reading LRIS file: /Users/chrismac/Work_UCR/Brian_Data_Reduc/PypeIt_run_files/Feb_2012/Red/Abell1689/Fits_files/r120223_0045.fits
[INFO]    :: Reading LRIS file: /Users/chrismac/Work_UCR/Brian_Data_Reduc/PypeIt_run_files/Feb_2012/Red/Abell1689/Fits_files/r120223_0045.fits
[INFO]    :: Using hard-coded BPM for det=2 on LRISr
[INFO]    :: Preparing a master arc frame
[INFO]    :: Reading LRIS file: /Users/chrismac/Work_UCR/Brian_Data_Reduc/PypeIt_run_files/Feb_2012/Red/Abell1689/Fits_files/r120223_0065.fits
[INFO]    :: Reading LRIS file: /Users/chrismac/Work_UCR/Brian_Data_Reduc/PypeIt_run_files/Feb_2012/Red/Abell1689/Fits_files/r120223_0065.fits
[INFO]    :: Reading LRIS file: /Users/chrismac/Work_UCR/Brian_Data_Reduc/PypeIt_run_files/Feb_2012/Red/Abell1689/Fits_files/r120223_0065.fits
[INFO]    :: Reading LRIS file: /Users/chrismac/Work_UCR/Brian_Data_Reduc/PypeIt_run_files/Feb_2012/Red/Abell1689/Fits_files/r120223_0065.fits
[INFO]    :: Reading LRIS file: /Users/chrismac/Work_UCR/Brian_Data_Reduc/PypeIt_run_files/Feb_2012/Red/Abell1689/Fits_files/r120223_0065.fits
[INFO]    :: Bias subtracting your image(s)
[INFO]    :: Using overscan to subtract

[ERROR]   :: Overscan sections do not match amplifier sections foramplifier 1
Traceback (most recent call last):
  File "/anaconda3/bin/run_pypeit", line 4, in <module>
    __import__('pkg_resources').run_script('pypeit==0.9.4.dev0', 'run_pypeit')
  File "/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 661, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1441, in run_script
    exec(code, namespace, namespace)
  File "/anaconda3/lib/python3.7/site-packages/pypeit-0.9.4.dev0-py3.7.egg/EGG-INFO/scripts/run_pypeit", line 17, in <module>
    rtval = run_pypeit.main(args)
  File "/anaconda3/lib/python3.7/site-packages/pypeit-0.9.4.dev0-py3.7.egg/pypeit/scripts/run_pypeit.py", line 99, in main
    pypeIt.reduce_all()
  File "/anaconda3/lib/python3.7/site-packages/pypeit-0.9.4.dev0-py3.7.egg/pypeit/pypeit.py", line 265, in reduce_all
    sci_dict = self.reduce_exposure(frames, bg_frames=bg_frames, std_outfile=std_outfile)
  File "/anaconda3/lib/python3.7/site-packages/pypeit-0.9.4.dev0-py3.7.egg/pypeit/pypeit.py", line 350, in reduce_exposure
    self.caliBrate.run_the_steps()
  File "/anaconda3/lib/python3.7/site-packages/pypeit-0.9.4.dev0-py3.7.egg/pypeit/calibrations.py", line 763, in run_the_steps
    getattr(self, 'get_{:s}'.format(step))()
  File "/anaconda3/lib/python3.7/site-packages/pypeit-0.9.4.dev0-py3.7.egg/pypeit/calibrations.py", line 239, in get_arc
    self.msarc = self.arcImage.build_image()
  File "/anaconda3/lib/python3.7/site-packages/pypeit-0.9.4.dev0-py3.7.egg/pypeit/arcimage.py", line 76, in build_image
    self.stack = self.process(bias_subtract=self.msbias, overwrite=overwrite, trim=True)
  File "/anaconda3/lib/python3.7/site-packages/pypeit-0.9.4.dev0-py3.7.egg/pypeit/processimages.py", line 535, in process
    self.bias_subtract(bias_subtract, trim=trim)
  File "/anaconda3/lib/python3.7/site-packages/pypeit-0.9.4.dev0-py3.7.egg/pypeit/processimages.py", line 428, in bias_subtract
    params=self.proc_par['overscan_par'])
  File "/anaconda3/lib/python3.7/site-packages/pypeit-0.9.4.dev0-py3.7.egg/pypeit/core/procimg.py", line 582, in subtract_overscan
    'amplifier {0}'.format(i+1))
  File "/anaconda3/lib/python3.7/site-packages/pypeit-0.9.4.dev0-py3.7.egg/pypeit/pypmsgs.py", line 269, in error
    raise PypeItError(msg)
pypeit.pypmsgs.PypeItError: Overscan sections do not match amplifier sections foramplifier 1

**Comment by csnap001** [comment]
I found a workaround to this issue. The following change to keck_lris.py ensures that the length of the array along the spectral direction for the overscan is the same as that for the data:

-954 section = '[:,{:d}:{:d}]'.format(xs*xbin, xe*xbin)
+954 section = '[{:d}:{:d},{:d}:{:d}]'.format(preline*ybin, (nydata-postline)*ybin,xs*xbin, xe*xbin)

This change is done in the postdata section of the read_lris() function. I note that @abostroem may have a slightly different issue because of the warning message:
[WARNING] :: Unexpected size for LRIS detector.  We expect you did some windowing...
but as far as I can tell this shouldn't be a problem. I have run some tests with this fix on the blue side as well and everything is working smoothly. This issue seems to have been a result of the nonzero postline for LRIS red.

**Comment by profxj** [comment]
This was addressed quite awhile ago but I suspect did
not propagate to the `pip` version.  Things are fine in 
the current *master*.
