### ISSUE TITLE
Slit trace failing LRIS blue 400/3400 560 dichroic from adjacent star slits

### ISSUE THREAD

**Issue by csnap001** [pypeit/PypeIt#680]
<img width="773" alt="Screen Shot 2019-05-09 at 4 10 59 PM" src="https://user-images.githubusercontent.com/10412412/57493146-a4eabd00-7278-11e9-9aa9-b7aee94b1929.png">
I am running the pypeit reduction pypeline on a 400 grism and 560 dichroic. I obtain the following error when running on the above detector: 
Traceback (most recent call last):
  File "/anaconda3/lib/python3.7/site-packages/pypeit-0.9.4.dev0-py3.7.egg/pypeit/calibrations.py", line 562, in get_slits
    write_qa=write_qa)
  File "/anaconda3/lib/python3.7/site-packages/pypeit-0.9.4.dev0-py3.7.egg/pypeit/traceslits.py", line 966, in run
    self._trim_slits(trim_slits=trim_slits, plate_scale=plate_scale)
  File "/anaconda3/lib/python3.7/site-packages/pypeit-0.9.4.dev0-py3.7.egg/pypeit/traceslits.py", line 768, in _trim_slits
    off_detector = (min_val > nspat) | (max_val < 0)
ValueError: operands could not be broadcast together with shapes (23,) (24,) 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda3/bin/run_pypeit", line 4, in <module>
    __import__('pkg_resources').run_script('pypeit==0.9.4.dev0', 'run_pypeit')
  File "/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 661, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1441, in run_script
    exec(code, namespace, namespace)
  File "/anaconda3/lib/python3.7/site-packages/pypeit-0.9.4.dev0-py3.7.egg/EGG-INFO/scripts/run_pypeit", line 17, in <module>
    rtval = run_pypeit.main(args)
  File "/anaconda3/lib/python3.7/site-packages/pypeit-0.9.4.dev0-py3.7.egg/pypeit/scripts/run_pypeit.py", line 99, in main
    pypeIt.reduce_all()
  File "/anaconda3/lib/python3.7/site-packages/pypeit-0.9.4.dev0-py3.7.egg/pypeit/pypeit.py", line 265, in reduce_all
    sci_dict = self.reduce_exposure(frames, bg_frames=bg_frames, std_outfile=std_outfile)
  File "/anaconda3/lib/python3.7/site-packages/pypeit-0.9.4.dev0-py3.7.egg/pypeit/pypeit.py", line 350, in reduce_exposure
    self.caliBrate.run_the_steps()
  File "/anaconda3/lib/python3.7/site-packages/pypeit-0.9.4.dev0-py3.7.egg/pypeit/calibrations.py", line 763, in run_the_steps
    getattr(self, 'get_{:s}'.format(step))()
  File "/anaconda3/lib/python3.7/site-packages/pypeit-0.9.4.dev0-py3.7.egg/pypeit/calibrations.py", line 564, in get_slits
    self.traceSlits.save_master(self.tslits_dict)
  File "/anaconda3/lib/python3.7/site-packages/pypeit-0.9.4.dev0-py3.7.egg/pypeit/traceslits.py", line 1044, in save_master
    hdu_trc.header['NSPEC'] = tslits_dict['nspec']
TypeError: 'NoneType' object is not subscriptable

I believe that this is due to an unmatched slit edge:
[WARNING] :: Missing a left edge for slit with right edge(s) at [152.98069713 250.21536791]
[WARNING] :: Adding one (and only one)

I have played with the parameters, but these slit edges are always found. I believe this is happening because the two slits are getting blended together (since they are both designated for stars) and so I would like to simply avoid searching for slits in this area. I am aware of the add and remove slit options, but this is implemented after the initial tracing of the slits and so the reduction must first work through this and crashes before any remedy can be performed. If I am correct about this issue I believe it would be beneficial to users to allow a selection of physical space (in pixels) over which to search for slits, in this way it would be possible to avoid problem slits before the tracing algorithm is performed. In any case, are there any other methods I may use currently?

**Comment by csnap001** [comment]
I have found a workaround to this issue by modifying the trace_slits.py file
+598: hold = []
...
+644: if(len(gd_right) > 2):
+645:        hold.append(right_xval[gd_right[2]])
...
+674: for i in range(0,len(hold)):
+675:     for j in range(0,len(tc_dict['right']['xval'])-1):
+676:           if tc_dict['right']['xval'][j] == hold[i]:
+677:                 tc_dict['right']['traces'] = np.delete(tc_dict['right']['traces'],j,1)

The line numbering may be off a bit as I introduced new messages to help debug the issue. Without this adjustment traceslits.py crashes because of the following:
767: off_detector = (min_val > nspat) | (max_val <0)
This happens because the number of right traces becomes imbalanced with the number of left traces and so you are comparing lists/arrays with different numbers of elements which fails in python. So I have simply removed the extra right traces from tc_dict that do not get an added in left slit to avoid this issue. The way I have done this may not be the most efficient (it is a kludge), but it currently functions on the mask that I am using.

**Comment by profxj** [comment]
Am closing this for now.  Be advised that
the slit tracing is getting a *major* overhaul.
