### ISSUE TITLE
PypeIt crashes with opaque error message if there is no science image in PypeIt file

### ISSUE THREAD

**Issue by jhennawi** [pypeit/PypeIt#697]
Try running pypeit on one of the dev suite pypeit files, but comment out the science exposure. The result you will get is below. A very uninformative trace. I think the pipeline should be able to run through the master files without a science frame. This is for example, what someone might want to do at a telescope to verify that their calibrations ran okay. I got around this, by creating a dummy science frame line in the pypeit file. Anyway, I think this should be fixed. 

[ERROR]   :: spectrograph.py 695 get_headarr() - Problem opening None.
Traceback (most recent call last):
  File "/Users/joe/python/PypeIt/pypeit/spectrographs/spectrograph.py", line 692, in get_headarr
    hdu = fits.open(filename)
  File "/Users/joe/anaconda3/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 148, in fitsopen
    raise ValueError('Empty filename: {!r}'.format(name))
ValueError: Empty filename: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/joe/anaconda3/bin//run_pypeit", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/Users/joe/python/PypeIt/bin/run_pypeit", line 17, in <module>
    rtval = run_pypeit.main(args)
  File "/Users/joe/python/PypeIt/pypeit/scripts/run_pypeit.py", line 84, in main
    logname=logname, show=args.show)
  File "/Users/joe/python/PypeIt/pypeit/pypeit.py", line 91, in __init__
    spectrograph_cfg_lines = self.spectrograph.config_specific_par(sci_file).to_config()
  File "/Users/joe/python/PypeIt/pypeit/spectrographs/keck_deimos.py", line 260, in config_specific_par
    if self.get_meta_value(scifile, 'dispname') == '600ZD':
  File "/Users/joe/python/PypeIt/pypeit/spectrographs/spectrograph.py", line 579, in get_meta_value
    headarr = self.get_headarr(ifile)
  File "/Users/joe/python/PypeIt/pypeit/spectrographs/spectrograph.py", line 695, in get_headarr
    msgs.error('Problem opening {0}.'.format(filename))
  File "/Users/joe/python/PypeIt/pypeit/pypmsgs.py", line 264, in error
    raise PypeItError(msg)
pypeit.pypmsgs.PypeItError: Problem opening None.

**Comment by profxj** [comment]
Isn't this the same as #645 ?
If so, close @jhennawi
