### ISSUE TITLE
docs are not building on develop

### ISSUE THREAD

**Issue by jhennawi** [pypeit/PypeIt#748]
We get this error:

python3 ./scripts/build_par_rst.py
Traceback (most recent call last):
  File "./scripts/build_par_rst.py", line 83, in <module>
    s = load_spectrograph(spec)
  File "/Users/joe/python/PypeIt/pypeit/spectrographs/util.py", line 85, in load_spectrograph
    return spectrographs.magellan_fire.MagellanFIRESpectrograph()
  File "/Users/joe/python/PypeIt/pypeit/spectrographs/magellan_fire.py", line 53, in __init__
    self.norders = 22
AttributeError: can't set attribute
make[1]: *** [apirst] Error 1
make: *** [html] Error 2

Also note that the sphinx.readme file should have a line on where one needs to go to view the updated docs locally. I know there is a html index file somewhere, but I always forget where it lives.

**Comment by profxj** [comment]
This barfs if the one or more of the spectrographs are busted.

**Comment by profxj** [comment]
solved.
