### ISSUE TITLE
Error when co-adding/extracting 1D XS spectrum

### ISSUE THREAD

**Issue by keheintz** [pypeit/PypeIt#828]
Hello, when trying to run the pypeit_coadd_1dspec on the reduced X-shooter VIS arm science I get the following error message:

Traceback (most recent call last):
  File "//anaconda/envs/py36/bin/pypeit_coadd_1dspec", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/Users/keheintz/PypeIt/bin/pypeit_coadd_1dspec", line 11, in <module>
    coadd_1dspec.main(args)
  File "/Users/keheintz/PypeIt/pypeit/scripts/coadd_1dspec.py", line 72, in main
    norder = abs(ext_final['ECHORDER'] - ext_first['ECHORDER']) + 1
  File "//anaconda/envs/py36/lib/python3.6/site-packages/astropy/io/fits/header.py", line 148, in __getitem__
    card = self._cards[self._cardindex(key)]
  File "//anaconda/envs/py36/lib/python3.6/site-packages/astropy/io/fits/header.py", line 1708, in _cardindex
    raise KeyError(f"Keyword {keyword!r} not found.")
KeyError: "Keyword 'ECHORDER' not found."

Any solution on how to fix this?
Thanks, Kasper

**Comment by jhennawi** [comment]
It is known that co-adding does not work in master. This is being fixed in the deimos_merge3 branch. If you swtich to that branch, coadding should work although the documentation is not great at the moment. You can bug us in Slack though.

**Comment by profxj** [comment]
Closing this Issue as it relates to the deprecated coadd1d script.
