### ISSUE TITLE
Frametype user error

### ISSUE THREAD

**Issue by profxj** [pypeit/PypeIt#852]
Would be good to have the error print out the item(s) that
are incorrect:

INFO]  :: Using user-provided frame types.
Traceback (most recent call last):
 File "/Users/ebeling/anaconda3/envs/pypeit/bin/run_pypeit", line 17, in <module>
  rtval = run_pypeit.main(args)
 File "/Users/ebeling/anaconda3/envs/pypeit/lib/python3.7/site-packages/pypeit/scripts/run_pypeit.py", line 80, in main
  logname=logname, show=args.show)
 File "/Users/ebeling/anaconda3/envs/pypeit/lib/python3.7/site-packages/pypeit/pypeit.py", line 116, in __init__
  self.fitstbl.finalize_usr_build(frametype, setups[0])
 File "/Users/ebeling/anaconda3/envs/pypeit/lib/python3.7/site-packages/pypeit/metadata.py", line 419, in finalize_usr_build
  self.get_frame_types(user=frametype)
 File "/Users/ebeling/anaconda3/envs/pypeit/lib/python3.7/site-packages/pypeit/metadata.py", line 1172, in get_frame_types
  type_bits[indx] = self.type_bitmask.turn_on(type_bits[indx], flag=ftypes.split(','))
 File "/Users/ebeling/anaconda3/envs/pypeit/lib/python3.7/site-packages/pypeit/bitmask.py", line 340, in turn_on
  _flag = self._prep_flags(flag)
 File "/Users/ebeling/anaconda3/envs/pypeit/lib/python3.7/site-packages/pypeit/bitmask.py", line 113, in _prep_flags
  raise ValueError('Some bit names not recognized.')
ValueError: Some bit names not recognized.

**Comment by kbwestfall** [comment]
Addressed in #855
