### ISSUE TITLE
Trace edges script is broken in develop

### ISSUE THREAD

**Issue by jhennawi** [pypeit/PypeIt#881]
pypeit_trace_edges -f keck_nires_nires.pypeit

[ERROR]   :: combineimage.py 52 __init__() - Combineimage requires a list of files to instantiate
Traceback (most recent call last):
  File "/Users/joe/opt/anaconda3/bin//pypeit_trace_edges", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/Users/joe/python/PypeIt/bin/pypeit_trace_edges", line 16, in <module>
    sys.exit(trace_edges.main(trace_edges.parser()))
  File "/Users/joe/python/PypeIt/pypeit/scripts/trace_edges.py", line 137, in main
    msbias = buildimage.buildimage_fromlist(spec, det, bias_par, bias_files)
  File "/Users/joe/python/PypeIt/pypeit/images/buildimage.py", line 137, in buildimage_fromlist
    combineImage = combineimage.CombineImage(spectrograph, det, frame_par['process'], file_list)
  File "/Users/joe/python/PypeIt/pypeit/images/combineimage.py", line 52, in __init__
    msgs.error('Combineimage requires a list of files to instantiate')
  File "/Users/joe/python/PypeIt/pypeit/pypmsgs.py", line 264, in error
    raise PypeItError(msg)
pypeit.pypmsgs.PypeItError: Combineimage requires a list of files to instantiate

**Comment by profxj** [comment]
To be clear, the unit test is not failing which passes.

This is some other use mode.

**Comment by profxj** [comment]
Fixed by PR #882
