### ISSUE TITLE
Splicing crash in pypeit_sensfunc

### ISSUE THREAD

**Issue by profxj** [pypeit/PypeIt#916]
After churning for ~1 hour on telluric fitting, the code crashed on DEIMOS
where I was attempting to work on detectors 3 and 7.  

The QA plots to the screen looked ok as the code progressed.

Here is the traceback:

```
[INFO]    :: sensfunc.py 241 splice() - Merging sensfunc for 2 detectors [3, 7]
[INFO]    :: sensfunc.py 267 splice() - Interpolating over gaps
Traceback (most recent call last):
  File "/home/xavier/Projects/anaconda3/bin/pypeit_sensfunc", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/data/Projects/Python/PypeIt/bin/pypeit_sensfunc", line 11, in <module>
    sensfunc.main(args)
  File "/data/Projects/Python/PypeIt/pypeit/scripts/sensfunc.py", line 167, in main
    sensobj.run()
  File "/data/Projects/Python/PypeIt/pypeit/sensfunc.py", line 132, in run
    self.wave_sens, self.sensfunc = self.splice(self.wave_sens)
  File "/data/Projects/Python/PypeIt/pypeit/sensfunc.py", line 271, in splice
    zero_values = interp_func(wave_splice[zeros])
  File "/home/xavier/Projects/anaconda3/lib/python3.7/site-packages/scipy/interpolate/polyint.py", line 79, in __call__
    y = self._evaluate(x)
  File "/home/xavier/Projects/anaconda3/lib/python3.7/site-packages/scipy/interpolate/interpolate.py", line 663, in _evaluate
    below_bounds, above_bounds = self._check_bounds(x_new)
  File "/home/xavier/Projects/anaconda3/lib/python3.7/site-packages/scipy/interpolate/interpolate.py", line 695, in _check_bounds
    raise ValueError("A value in x_new is above the interpolation "
ValueError: A value in x_new is above the interpolation range.
```

I suggest it be modified to avoid a full crash.

**Comment by profxj** [comment]
Addressed by PR #918
