### ISSUE TITLE
pypeit_show_1dspec bug

### ISSUE THREAD

**Issue by profxj** [pypeit/PypeIt#932]
We can no longer view QL outputs:

```
(base) profx> pypeit_show_1dspec Science/spec1d_b27-J1217p3905_KASTb_2015May20T045733.560.fits --list
 FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison (arraysetops.py:569)
Traceback (most recent call last):
  File "/data/Projects/Python/PypeIt/pypeit/scripts/show_1dspec.py", line 43, in main
    raise ValueError("This is an ugly hack until the DataContainer bug is fixed")
ValueError: This is an ugly hack until the DataContainer bug is fixed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/Projects/Python/PypeIt/pypeit/core/telluric.py", line 565, in general_spec_reader
    raise ValueError("This is an ugly hack until the DataContainer bug is fixed")
ValueError: This is an ugly hack until the DataContainer bug is fixed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xavier/Projects/anaconda3/bin/pypeit_show_1dspec", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/data/Projects/Python/PypeIt/bin/pypeit_show_1dspec", line 11, in <module>
    show_1dspec.main(args)
  File "/data/Projects/Python/PypeIt/pypeit/scripts/show_1dspec.py", line 46, in main
    wave, flux, flux_ivar, flux_mask, meta_spec, head = general_spec_reader(args.file)
  File "/data/Projects/Python/PypeIt/pypeit/core/telluric.py", line 589, in general_spec_reader
    counts_mask = onespec.mask.astype(bool)
AttributeError: 'NoneType' object has no attribute 'astype'
```

**Comment by jhennawi** [comment]
Looks like you just need to change my hack to use WAVE_BOX rather than WAVE_OPT. Or you can use another field. Unfortunately when  a file reader reads in garbage, we are forced into such corners.

**Comment by profxj** [comment]
Deal with, I think.
